### ISSUE TITLE
Add message to thrown Fido2VerificationException

### ISSUE THREAD

**Issue by abergs** [passwordless-lib/fido2-net-lib#10]
To help debugging/reporting

**Comment by aseigler** [comment]
We should probably come up with a standard exception message format for the whole project and adhere to that.

**Comment by abergs** [comment]
Yes. I think that message standard should include the expected and supplied value, similiar to unit testing exceptions: "Type was invalid. Expected 'create' but was 'something else'

**Comment by abergs** [comment]
Let's rewrite them where possible per my suggestion above. Pattern:
"{COMPLAINT/MESSAGE}. Expected 'X' but was 'Y'

The expected but was should only be added "where it makes sense".

For null values we might as well throw:
"'A' was null. Expected string but was null".

I can write a new constructor which formats it this way.

**Comment by m7nar110** [comment]
The new version is fun

**Comment by iamcarbon** [comment]
@abergs I think we made good progress on the error messages over the last 4 years. The messages are pretty good now! Can we close this issue?

**Comment by abergs** [comment]
We have indeed @iamcarbon
