### ISSUE TITLE
Coding style for conditions

### ISSUE THREAD

**Issue by Shtong** [passwordless-lib/fido2-net-lib#130]
I'm creating this issue to specifically tackle the subject of condition formatting already mentioned in #87. I've also added some suggestions I had in mind after seeing some of the library's code. I'm ready to fix these, but of course I'll only do it if there's a general agreement that it should be done!

### 1. Inverted conditions
In C# code, we usually write conditions in which the subject of the test is written on the left of comparison operators, and the value we compare it to comes on the right. So for example, we would write:

```cs
if (someObject.Method() > 7)
```

instead of:

```cs
if (7 < someObject.Method())
```

Today most of the library uses the second form. I propose we change them to use the standard .NET order.

### 2. Explicit boolean comparisons

The library usually uses explicit boolean comparisons, which is also unusual in C#, where we usually see implicit comparisons. Instead of:

```cs
if (someObject.Method() == true)
```

we would write:

```cs
if(someObject.Method())
```

This change doesn't really do anything else than making the code more concise, and make it closer than what we usually see in C#.

### 3. String comparisons

When looking for an exact equality between two strings, there is no difference in C# between `string1 == string2` and `string1.Equals(string2)` (except in the case where `string1` is `null`). Currently, the Fido2 library uses a lot of comparisons using `Equals` like we would use in Java.

In order to improve in comparisons across the library, I propose that we compare `==` instead of `Equals`, when there is no difference between the two.

---

There it is. What do you think ?

**Comment by iamcarbon** [comment]
@abergs I believe we've all our condition logic to read right to left. Can we close this issue?

**Comment by abergs** [comment]
I agree
