### ISSUE TITLE
Migrate from Newtonsoft to System.Text.Json

### ISSUE THREAD

**Issue by maxkuzmin** [passwordless-lib/fido2-net-lib#146]
Since in asp.net core 3 internal support of Newtonsoft is removed, now we need to use `.AddNewtonsoftJson();` to make this lib working. It seems quite redundant. Is it possible to migrate this library from Newtonsoft to System.Text.Json?

**Comment by abergs** [comment]
@maxkuzmin It needs to be investigated, it's not as easy as it sounds.

System.Text.Json is optimized for speed and therefore cut features to obtain that speed.

Because of how WebAuthn works we need to pass base64 strings and rename models, e.g.

```csharp
 [JsonProperty("userHandle")]
 [JsonConverter(typeof(Base64UrlConverter), Required.AllowNull)]
 public byte[] UserHandle { get; set; }
```

**Comment by abergs** [comment]
https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to
