### ISSUE TITLE
FYI: spec violation in current MDS data causing parser errors

### ISSUE THREAD

**Issue by mackie1001** [passwordless-lib/fido2-net-lib#181]
The spec clearly states that `authenticatorVersion` is an `unsigned short` (i.e. a UInt16) but as of recently new entries from Yubico are using values well north of 2^16. 

Example is AAGUID `2fc0579f-8113-47ea-b116-bb5a8db9202a` which is for the YubiKey 5 NFC version 5.2.x - it looks like they've just padded out the firmware version to create the `authenticatorVersion` value.

```
Error initialising MDS client 'Fido2MetadataServiceRepository'
Newtonsoft.Json.JsonSerializationException: Error converting value 502000 to type 'System.UInt16'. Path 'authenticatorVersion', line 1, position 1337.
 ---> System.OverflowException: Value was either too large or too small for a UInt16.
```

I wonder if it's worth just changing the model in the lib to accomodate this (i.e. just bump it up to a UInt32).

Not the first spec violation I've encountered with that service. Does anyone have a contact this can be reported to?

**Comment by aseigler** [comment]
No, we should not change the lib.  This is definitely a typo in the MDS data that the vendor must fix, it is clearly [against spec](https://fidoalliance.org/specs/fido-v2.0-rd-20180702/fido-metadata-statement-v2.0-rd-20180702.html#widl-MetadataStatement-authenticatorVersion).

**Comment by aseigler** [comment]
To me, the biggest problem is that if an entry fails to load, we drop everything and walk away instead of logging a single entry failed to parse and moving on to the next entry.  We should probably handle single entry parse failure more elegantly.

**Comment by mackie1001** [comment]
That's what I've done for now in my implementation - I'd like to revisit the MDS stuff I did and add in some improvements like you describe.

**Comment by aseigler** [comment]
> That's what I've done for now in my implementation - I'd like to revisit the MDS stuff I did and add in some improvements like you describe.

Yeah, for now I went [here](https://github.com/abergs/fido2-net-lib/blob/f976dc4cb8635468df51be2283338e2aafa6c6a7/Src/Fido2.AspNet/DistributedCacheMetadataService.cs#L110) and removed the throw, which got the desired result but probably isn't the cleanest thing to do.  Perhaps catch JsonSerializationException and don't throw those, or something like that.

**Comment by aseigler** [comment]
The offending MDS entry got fixed overnight, but servers that got the TOC yesterday may cache it until July 20.

**Comment by aseigler** [comment]
Pretty sure this is non-issue now, particularly with the MDS3 changes.
