### ISSUE TITLE
Minor inconsistency between AllowCredentials and ExcludeCredentials

### ISSUE THREAD

**Issue by MichaelGrafnetter** [passwordless-lib/fido2-net-lib#191]
Hi, there is a tiny inconsistency in the API:
```cs
public class CredentialCreateOptions : Fido2ResponseBase
{
    ...
    public List<PublicKeyCredentialDescriptor> ExcludeCredentials { get; set; }
}

```
vs.
```cs
public class AssertionOptions : Fido2ResponseBase
{
    ...
    public IEnumerable<PublicKeyCredentialDescriptor> AllowCredentials { get; set; }
}
```

I therefore propose changing `AllowCredentials` to `List<PublicKeyCredentialDescriptor>`. This should not be a breaking change, as `List` is still `IEnumerable`.

**Comment by 6Hat** [comment]
Likely I am missing it... I see ExlcludeCredentials in the library, but what happened to AllowCredentials? See:
![image](https://user-images.githubusercontent.com/32961864/116406306-5deb8e80-a7e5-11eb-9c1c-a3200f0bbbdd.png)
