### ISSUE TITLE
not working with apples faceid

### ISSUE THREAD

**Issue by de-peter** [passwordless-lib/fido2-net-lib#209]
hi, i'm using fido2 for mfa, i can register my credentials with faceid, but when trying to authenticate faceid isn't activated, it's saying to attach my security-key. With Windows-Hello, it's working fine.

any ideas what i'm doing wrong?

**Comment by abergs** [comment]
Do you get any error messages?

**Comment by de-peter** [comment]
no, it only gives the message that i have to attach my security key...

i think, that normally he should ask whether i want to use faceid...

**Comment by mackie1001** [comment]
I can confirm that this is working for me using 2.0.2 on an iOS 15 iPad Pro, ditto for touch ID on an iPhone 8 Plus.
