### ISSUE TITLE
fido2-net-lib library does not handle the ECC secP256k1 curve properly

### ISSUE THREAD

**Issue by rodheath** [passwordless-lib/fido2-net-lib#233]
The fido2-net-lib library does not work correctly with tokens that use the ECC secP256k1 curve.

The library incorrectly maps COSE.EllipticCurve.P256K to ECCurve.NamedCurves.nistP256.

Correct support for ECC secP256k1 is obtained by mapping COSE.EllipticCurve.P256K to the secP256k1 curve which is available from ECCurve.CreateFromFriendlyName("secP256k1")

**Comment by aseigler** [comment]
Resolved by #234
