### ISSUE TITLE
pubKeyCredParams[n].alg serialization issues

### ISSUE THREAD

**Issue by StummeJ** [passwordless-lib/fido2-net-lib#263]
After upgrading `Fido2` from `1.1.0` to anything `2.0.0` or above we're seeing an incorrect serialization of the `publicKeyCredParams[n].alg` values.  I've seen some things about the `type` being serialized incorrectly to a number, but cannot find anything about the `alg` being serialized incorrectly as a string.  I also noticed there were some changes to the `alg` to move it from a `long` to an enum.

### New lib error:
![image](https://user-images.githubusercontent.com/3059647/140539096-7862a894-b5a2-4a88-9c80-e5189a96ea0c.png)

### New:
![image](https://user-images.githubusercontent.com/3059647/140538608-d7611409-1a74-4940-ad26-b9703568a785.png)
### Old:
![image](https://user-images.githubusercontent.com/3059647/140538658-94437d72-8a4f-46cc-82ac-761963ec0cd5.png)

**Comment by aseigler** [comment]
I can't reproduce this.  The strings coming out of the alg values are weird enough, but the dashes that are getting added in the middle are really bizarre.  Not really sure where that is coming from.

**Comment by Binaryraja** [comment]
With this change, We are unable to call navigator.credentials.create. Exception occurs. The same code works with Nuget Package 1.1.0 where the pubKeyCredParams[n] is hardcoded.

**Comment by iamcarbon** [comment]
@Binaryraja Were you able to figure this out?
