### ISSUE TITLE
Release 3.0

### ISSUE THREAD

**Issue by abergs** [passwordless-lib/fido2-net-lib#264]
We want to release 3.0 which is packed with changes.
Is there any more additions we want to make before releasing?

📦**Nuget package is available at**: https://www.nuget.org/packages/Fido2/3.0.0

Here are the release notes:

## 💥 Breaking change

- Improve code quality 4 @iamcarbon (#254)
- Drop net5.0 support & update depedencies @iamcarbon (#295)

## 🚀 Features and enhancements

- Drop net5.0 support & update depedencies @iamcarbon (#295)
- Refactored IMetadataService to be async and removed init-related methods @mackie1001 (#266)
- Add CancellationToken to Task methods @trejjam (#278)
- Add .Net 6 as supported framework @trejjam (#270)
- Improve Code Quality 7 @iamcarbon (#279)
- Enforce UV in attestation if required for registration @aseigler (#276)
- Add tests @aseigler (#269)
- Support Multiple Origins @Hinton (#237)
- Fix attestation certificate validation @adricasti (#261)
- Improve Code Quality 5 @iamcarbon (#259)
- Use System.Formats.Cbor @iamcarbon (#257)
- Move AndroidKey tests to System.Formats.Asn1, remove AsnElt @aseigler (#258)
- Improve code quality 4 @iamcarbon (#254)
- Improve code quality 3 @iamcarbon (#251)
- Migrate from Newtonsoft to System.Text.Json @iamcarbon (#249)
- Improve Code Quality 2 @iamcarbon (#244)
- Cleanup tests @iamcarbon (#247)
- Use .NET 5.0 SDK @iamcarbon (#245)
- Improve Code Quality @iamcarbon (#239)
- Support MDS3 @aseigler (#238)

## 🐛 Bug Fixes

- Avoid adding null Origin to Origins. Fixes #283. @abergs (#296)
- Enforce UV in attestation if required for registration @aseigler (#276)
- Fix attestation certificate validation @adricasti (#261)
- Fix for ECC Curve secP256k1 @rodheath (#234)
- Intercede bug fixes @rodheath (#229)

## 🧰 Maintenance & documentation

- Add TLS endpoint to Demo project launch config @tmarkovski (#297)
- Enforce UV in attestation if required for registration @aseigler (#276)
- Fix attestation certificate validation @adricasti (#261)
- Fix old links in readme @abergs (#262)
- Improve Code Quality 5 @iamcarbon (#259)
- Fix codecov badge in readme @abergs (#260)
- Move AndroidKey tests to System.Formats.Asn1, remove AsnElt @aseigler (#258)
- Remove left over remnants of MDS2 @aseigler (#253)
- Migrate from Newtonsoft to System.Text.Json @iamcarbon (#249)
- Remove require labels workflow @iamcarbon (#248)
- Use .NET 5.0 SDK @iamcarbon (#245)
- Improve Code Quality @iamcarbon (#239)
- Drop .NETStandard2.0 support on AspNet project @iamcarbon (#241)
- Adjust for .net foundation @abergs (#232)
- Release v3.0.0 @abergs (#264)

**Comment by adricasti** [comment]
Thanks for his release, would it be possible to push it to the NuGet repository that still contains the previous 2.0.2 release?

**Comment by abergs** [comment]
@adricasti I'm not sure what you mean? We will push it to nuget, but all the previous versions are still available on nuget:

https://www.nuget.org/packages/Fido2/

**Comment by abergs** [comment]
Fido2 3.0.0-bet1 is available on nuget: https://www.nuget.org/packages/Fido2/3.0.0-beta1

**Comment by aseigler** [comment]
> Is there any more additions we want to make before releasing?

Hoping we can get #266 in and I am going to work on #237 as well and get that one in as well.

**Comment by mackie1001** [comment]
I've published #266 now, interested in your thoughts @aseigler as I went a bit further than originally discussed.

**Comment by abergs** [comment]
FIdo2 3.0.0-beta 2 is pushed to nuget: https://www.nuget.org/packages/Fido2/3.0.0-beta2

**Comment by gingters** [comment]
Any chance that 3.0 could still support netcoreapp 3.1 for a little further?

I am working on integrating that into a larger code base that currently still needs to support 3.1 for a bit further while its currently in the process to being updated to .NET 6, but that will take some time (at least end of year) and we would need MDS3 support as deployment will be in environments that have no external network access.

Or would it be possible to backport MDS3 support into 2.x so that we can use that until 3.1 support can be dropped here?

**Comment by mackie1001** [comment]
3.1 -> 6.0 is actually pretty simple compared to previous upgrades we've been through but that doesn't account for organisational intertia of course. 
My suggestion would be to do a PR to backport MDS3 or create your own fork and handle it that way.

**Comment by abergs** [comment]
@mackie1001 I'll make it happen. I've been reviewing and it looks good so far.

**Comment by damienbod** [comment]
@mackie1001 Tried updating and failed, got stuck at the DB bits as well. I will invest more time and see if I can figure this out.

Greetings Damien

**Comment by namespacedevbox** [comment]
> @mackie1001 Tried updating and failed, got stuck at the DB bits as well. I will invest more time and see if I can figure this out.
> 
> All FIDO2 bits are inside the FIDO2 folder
> 
> https://github.com/damienbod/AspNetCoreIdentityFido2Mfa/tree/main/AspNetCoreIdentityFido2Mfa/Fido2
> 
> https://github.com/damienbod/AspNetCoreIdentityFido2Mfa/tree/main/AspNetCoreIdentityFido2Passwordless/Fido2
> 
> And the store.
> 
> https://github.com/damienbod/AspNetCoreIdentityFido2Mfa/blob/main/AspNetCoreIdentityFido2Passwordless/Data/ApplicationDbContext.cs#L14
> 
> Greetings Damien

Migrate to v3

-  Update nuget to v3.0.0-beta6
-  Update lib init `Origins = new HashSet<string> { "http://example.com" }`
-  Change JSON serialization / deserialization to JsonSerializer.Serialize / JsonSerializer.Deserialize in your controllers
-  In credential methods change model 
```
var exts = new AuthenticationExtensionsClientInputs
{
     Extensions = true,
     UserVerificationMethod = true
};
```
- In credential methods add cancelation token in params `IsCredentialIdUniqueToUserAsyncDelegate callback = async (args, cancellationToken) => { ... }`

- In assertion methods change model
```var exts = new AuthenticationExtensionsClientInputs()
{ 
   UserVerificationMethod = true
};```

**Comment by namespacedevbox** [comment]
> @mackie1001 Tried updating and failed, got stuck at the DB bits as well. I will invest more time and see if I can figure this out.
> 
> All FIDO2 bits are inside the FIDO2 folder
> 
> https://github.com/damienbod/AspNetCoreIdentityFido2Mfa/tree/main/AspNetCoreIdentityFido2Mfa/Fido2
> 
> https://github.com/damienbod/AspNetCoreIdentityFido2Mfa/tree/main/AspNetCoreIdentityFido2Passwordless/Fido2
> 
> And the store.
> 
> https://github.com/damienbod/AspNetCoreIdentityFido2Mfa/blob/main/AspNetCoreIdentityFido2Passwordless/Data/ApplicationDbContext.cs#L14
> 
> Greetings Damien

Migrate to v3

- Update nuget to v3.0.0-beta6
- Update lib init `Origins = new HashSet<string> { "http://example.com" }`
- Remove `.AddNewtonsoftJson();` in builder.Services.AddControllers().AddNewtonsoftJson();
- Change JSON serialization / deserialization to JsonSerializer.Serialize / JsonSerializer.Deserialize in your controllers
- In credential methods change model 
```
var exts = new AuthenticationExtensionsClientInputs
{
     Extensions = true,
     UserVerificationMethod = true
};
```
- In credential methods add cancelation token in params
`IsCredentialIdUniqueToUserAsyncDelegate callback = async (args, cancellationToken) => { ... }`
- In assertion methods change model
```
var exts = new AuthenticationExtensionsClientInputs()
{ 
   UserVerificationMethod = true
};
```
- In assertion methods add cancelation token in params
 `IsUserHandleOwnerOfCredentialIdAsync callback = async (args, cancellationToken) => { ... }`
- In JS function getCredentials add to response userHandle
```
 let authData = new Uint8Array(credential.response.authenticatorData);
    let clientDataJSON = new Uint8Array(credential.response.clientDataJSON);
    let rawId = new Uint8Array(credential.rawId);
    let sig = new Uint8Array(credential.response.signature);
    let userHandle = new Uint8Array(credential.response.userHandle);
    const data = {
        id: credential.id,
        rawId: coerceToBase64Url(rawId),
        type: credential.type,
        extensions: credential.getClientExtensionResults(),
        response: {
            authenticatorData: coerceToBase64Url(authData),
            clientDataJson: coerceToBase64Url(clientDataJSON),
            userHandle: userHandle !== null ? coerceToBase64Url(userHandle) : null,
            signature: coerceToBase64Url(sig)
        }
    };
```

**Comment by damienbod** [comment]
Thanks @namespacedevbox I give this a try

**Comment by damienbod** [comment]
@namespacedevbox Updated now, thanks a million. Most of the migration worked. I was not able to update the **js** login scripts to use the **userHandle**, this causes errors if I add this. Is this a bug maybe?

https://github.com/damienbod/AspNetCoreIdentityFido2Mfa/blob/main/AspNetCoreIdentityFido2Passwordless/wwwroot/js/passwordless.login.js#L96

Everything else seems to work.

The migration was great. This was missing, maybe you could add it, if this is for the docs =>

new CredentialMakeResult( instead of new CredentialMakeResult {}

**Comment by damienbod** [comment]
Also I use this at the moment:

```
Origins = new HashSet<string> { _optionsFido2Configuration.Value.Origin },
```

HashSet<string> Origins is not really a good type to serialize, deserialize to/from a configuration, maybe use a different type?

**Comment by namespacedevbox** [comment]
@damienbod What is the message of the error?

my function that receives options and returns data back
```
async function createCredentials(credentialOptionsJson) {
    let credentialOptions = JSON.parse(credentialOptionsJson);
    credentialOptions.challenge = coerceToArrayBuffer(credentialOptions.challenge);
    credentialOptions.user.id = coerceToArrayBuffer(credentialOptions.user.id);
    credentialOptions.excludeCredentials = credentialOptions.excludeCredentials.map((c) => {
        c.id = coerceToArrayBuffer(c.id);
        return c;
    });

    let credential = await navigator.credentials.create({
        publicKey: credentialOptions
    });

    let attestationObject = new Uint8Array(credential.response.attestationObject);
    let clientDataJSON = new Uint8Array(credential.response.clientDataJSON);
    let rawId = new Uint8Array(credential.rawId);

    const data = {
        id: credential.id,
        rawId: coerceToBase64Url(rawId),
        type: credential.type,
        extensions: credential.getClientExtensionResults(),
        response: {
            attestationObject: coerceToBase64Url(attestationObject),
            clientDataJSON: coerceToBase64Url(clientDataJSON)
        }
    };

    return JSON.stringify(data);
}
```

**Comment by damienbod** [comment]
I get the following warning:

```
credentialId: null, counter: 0, status: 'error', errorMessage: 'Userhandle was empty DOMString. It should either be null or have a value.'}
```

**Comment by damienbod** [comment]
Added a PR to improve the Fido2 configuration

https://github.com/passwordless-lib/fido2-net-lib/pull/306

**Comment by namespacedevbox** [comment]
I have an error only on android:
`Userhandle was empty DOMString. It should either be null or have a value.`

**Comment by abergs** [comment]
Version 3.0.0 is now released. 

* Nuget: https://www.nuget.org/packages/Fido2/3.0.0
* Github release: https://github.com/passwordless-lib/fido2-net-lib/releases/tag/v3.0.0

Please open new issues for bug reports!
