### ISSUE TITLE
One namespace on the whole project

### ISSUE THREAD

**Issue by trejjam** [passwordless-lib/fido2-net-lib#272]
Hi,
I did notice that the project define only one namespace (Fido2NetLib). It is a general practice, that namespaces match to folder structure. Do you mind, if I fix it?

**Comment by abergs** [comment]
I'm not convinced of the value of this change. To me it feels like it would decrease discoverability of classes by introducing unnecessary structure.

I'm open to hear arguments.

**Comment by trejjam** [comment]
I never thought to do otherwise. This library is the first I see with a single namespace all over projects. (I do not count Tests & Demo)

For me it brings clarity. When I want to use a type, I know where it comes from.

A simple example is hypothetical type `Fido2.Lib.DependencyInjection.FidoExtensions`. When you see `FidoExtensions`, you can expect a static class with static methods with the `this` keyword. But you do not know what it extends. When you see the namespace you know that it adds to the `Fido.Lib` extension methods related to `DependencyInjection`.

An example is `Microsoft` standard libraries which are divided by scopes.

I do understand that since you have got used to it...

**Comment by iamcarbon** [comment]
This sounds like it would introduce a lot of churn to the codebase and force a lot of downstream consumers to react to a change with no benefits. I'm unconvinced.

**Comment by trejjam** [comment]
I recently noticed (felt) a tiny benefit. When you add a new public type to the codebase consumers of the library have 100% chance that they will got "hit" by it when they have the type of the same name in the current scope. With namespace-per-folder, you have better damage control.

Single namespace has a feeling of the "god" file - everything in a single file.

I understood your point of view. Feel free to close the issue if you want.

**Comment by kwaclaw** [comment]
In principle, having namespaces match the folder structure is not a bad idea, but there are also downsides.

Any restructuring of the folder structure breaks that guideline unless you also rename the namespaces. 

In my work I decide on a case by case basis, often when I move code files into a subdirectory I adjust the namespaces only if the restructuring has meaning beyond simple file organization.
