### ISSUE TITLE
Check UserVerified in attestation response

### ISSUE THREAD

**Issue by dIeGoLi** [passwordless-lib/fido2-net-lib#275]
https://github.com/passwordless-lib/fido2-net-lib/blob/3b4478c8c61db7b89f838eba1d9fe839a625b2a7/Src/Fido2/AuthenticatorAttestationResponse.cs#L116

Using external authenticators with an android device does not support user verification yet. If the application does requires user verification, registration of the authenticator will be successful but login not. Because when registering, the UserVerified flag is not checked, in contrast to [assertion response](https://github.com/passwordless-lib/fido2-net-lib/blob/3b4478c8c61db7b89f838eba1d9fe839a625b2a7/Src/Fido2/AuthenticatorAssertionResponse.cs#L142). That is a little bit inconsistent. It seems to be very easy to check that flag. I don't understand why this check should be configurable, as the comment indicates. 
Why don't we just activate this check?

**Comment by aseigler** [comment]
Thanks for bringing this up!
