### ISSUE TITLE
Version 2.0.2 NuGet package does not contain Origins property

### ISSUE THREAD

**Issue by devjared1** [passwordless-lib/fido2-net-lib#286]
The `Fido2Configuration` model does not contain the `Origins` property, only `Origin`, but the `Demo` project does contain the `Origins` property. Maybe I am not adding the correct NuGet packages. Here is a screenshot of the packages I installed along with the error in Visual Studio <br><br>
![image](https://user-images.githubusercontent.com/71391311/156658981-f58cf4f9-82e2-435f-8bbf-0b04987bd1a8.png)<br>
![image](https://user-images.githubusercontent.com/71391311/156659107-7af86530-880c-4c44-bb9f-bfca655da996.png)

**Comment by abergs** [comment]
You need to include prerelease to have the new Origins property. It's only available in 3.0 which is still considered a pre-release (but available on nuget)
