### ISSUE TITLE
NuGet claims <Net5.0 support on Release 2.0.2

### ISSUE THREAD

**Issue by yeroc-sebrof** [passwordless-lib/fido2-net-lib#294]
Hi folks,

NuGet still claims NetStandard2.0 and NetCore3.0 support for Release 2.0.2, a whole day's tinkering with NetCore3.1 and it doesn't seem to work and it looks to me that >=Net5.0 is already a requirement? I eventually found issue #246 which stated the aim to remove NetCore support - `We therefore push forward with .NET 5 as requirement` - but this looks like it was closed after 2.0.2?

Can I just have confirmation if 2.0.2 is meant to be supporting NetCore3.1?

If 2.0.2 is not supporting that version can the NuGet page be changed please?

Cheers!

**Comment by abergs** [comment]
@yeroc-sebrof NetStandard2.0 was dropped after the release. You can verify it by looking at the tag for [v2.0.2](https://github.com/passwordless-lib/fido2-net-lib/commits/v2.0.2) or the [commit history of master](https://github.com/passwordless-lib/fido2-net-lib/commits/master?after=db931bdba20aadc0743184fc9b0383a88b56ce02+34&branch=master&qualified_name=refs%2Fheads%2Fmaster)
