### ISSUE TITLE
.net without active directory

### ISSUE THREAD

**Issue by mdonogmaunreal** [passwordless-lib/fido2-net-lib#309]
Is it possible to use .net implementation without using active directory.

We have a .net mvc app publicly available and would like to go passwordless login - using active directory is out of the question as Microsoft charge $6 per user which blows costs out for us

**Comment by aseigler** [comment]
Perhaps I am missing something or misinterpreting this question, but other than a branch I worked on many years ago, I don't know of any mention of Active Directory, either on prem or Azure in this project at all, and certainly there is no dependency.  You can use any data storage of your choosing.

**Comment by abergs** [comment]
There is absolutely no dependency on active directory. You can use Fido2-net-lib without it.
If self-hosting fido2-net-lib is complicated for you, we recommend using the API we host at https://www.passwordless.dev/
