### ISSUE TITLE
Feedback on using library for Apple App Attest

### ISSUE THREAD

**Issue by Sebbs128** [passwordless-lib/fido2-net-lib#319]
I've recently had to implement app validation on a REST API for Apple's App Attest Service (which is based around issuing a WebAuthn Attestation object). Apple's documentation is located at https://developer.apple.com/documentation/devicecheck/establishing_your_app_s_integrity (the WebAuthn Attestation specific stuff is at https://developer.apple.com/documentation/devicecheck/validating_apps_that_connect_to_your_server, which was previously mentioned in #184).

Unfortunately, due to reasons I'll detail below, the primary classes from Fido2NetLib (mainly `AuthenticatorAttestationResponse.VerifyAsync()`) can't be entirely used in this scenario. So I wanted to offer this feedback/open a discussion with the aim of being able to use Fido2NetLib entirely in some future update.

1. The main roadblock is that the `AttestationObject.Fmt` for Apple's App Attest Service has a value of `apple-appattest`. Currently there's no way to inject custom implementations of `AttestationVerifier`, so we'll get a `Fido2VerificationException` thrown from `AuthenticatorAttestationResponse.VerifyAsync()`. (A hack-around by changing `ParsedAttestationObject.Fmt` isn't possible as this property doesn't have a publicly accessible setter). In #184 mackie1001 suggested having attestation formats pluggable (and aseigler mentioned structural refactoring around this for v2.0), however I'm not sure if that was heading to an injectable `AttestationVerifier` factory or resolver that would be needed in this situation. (If it isn't and nobody else is working on one, I could see about submitting a PR for this if I can find the time).

2. Another difficulty is that `apple-appattest` (and the corresponding root CA) isn't listed in the spec's Defined Attestation Statement Formats. Because of 1. I didn't continue investigating this. However, would I be correct that supplying a custom implementation of `IMetadataService` to `AuthenticatorAttestationResponse.VerifyAsync()` that would provide the Apple App Attest Root CA from https://www.apple.com/certificateauthority/private/ would be all that is needed to complete the validation of certificates supplied through the attestation statement?

3. Steps 5 and 9 of Apple's documentation mentions to verify the `credentialId` and SHA256 hash of the `credCert` public key against the `keyId` (obtained from `DCAppAttestService.shared.generateKey()`, and supplied to `DCAppAttestService.shared.attestKey()` to generate the attestation object). The existing `Apple` implementation of `AttestestationVerifier` compares those values from the attestation object itself, but doesn't provide a way to check them against some externally provided value. I suppose this could be passed in a delimited `clientDataJson`, but points to extend the current classes to achieve this don't currently exist (going back to 1.)

I'm unsure if there might be any similar potential difficulties around the assertion objects as I'm not currently using them or the receipts mentioned in the Apple documentation in our REST API, but likely will at some point in the future.

Thanks for what looks like a fantastic library at the moment (and certainly the premier library for working with WebAuthn objects in .NET). I appreciate any advice or concerns about the above points you all may have.

**Comment by Sebbs128** [comment]
Thanks for the quick response.

Here's a sample attestation I can share from the App Attest Service. (Note that the certificates in the attestation statements have expired).

```
o2NmbXRvYXBwbGUtYXBwYXR0ZXN0Z2F0dFN0bXSiY3g1Y4JZAtwwggLYMIICXqADAgECAgYBgtObIJkwCgYIKoZIzj0EAwIwTzEjMCEGA1UEAwwaQXBwbGUgQXBwIEF0dGVzdGF0aW9uIENBIDExEzARBgNVBAoMCkFwcGxlIEluYy4xEzARBgNVBAgMCkNhbGlmb3JuaWEwHhcNMjIwODI0MDYwNTM1WhcNMjIwODI3MDYwNTM1WjCBkTFJMEcGA1UEAwxAZTBiMzA5M2JmYzI0NDc0OTNhNGM4MGY2NjAxODFiYThhYTMxYTg5NGU4NTdjYTM2ZTEyMDkwMWIzZTdlMTMwOTEaMBgGA1UECwwRQUFBIENlcnRpZmljYXRpb24xEzARBgNVBAoMCkFwcGxlIEluYy4xEzARBgNVBAgMCkNhbGlmb3JuaWEwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASzA9dUXjxHkqdBGLAwBj7OZ0bJ5h3c58L4ZDfKSFTuDfMLVrVNDvitaR8yj5Pf0hVSZ+GoFhoDViUi4FBXIdCgo4HiMIHfMAwGA1UdEwEB/wQCMAAwDgYDVR0PAQH/BAQDAgTwMG8GCSqGSIb3Y2QIBQRiMGCkAwIBCr+JMAMCAQG/iTEDAgEAv4kyAwIBAb+JMwMCAQG/iTQXBBVWTlA1QTlTMjJWLjc2UjM4N01BVlqlBgQEc2tzIL+JNgMCAQW/iTcDAgEAv4k5AwIBAL+JOgMCAQAwGQYJKoZIhvdjZAgHBAwwCr+KeAYEBDE1LjUwMwYJKoZIhvdjZAgCBCYwJKEiBCClkteVRl5PINOO66qfPHoeNy+ZAKc8GzJMzQ+VjwAqczAKBggqhkjOPQQDAgNoADBlAjEAhghceRlBJEarkLeQcPvM1K895/k3IKSdA6y0kS7KdcjFpQ8+ZNH7ywC+n/CV5MVBAjAu0XfZ+a5nngecM9etqiX8HEaCEHuySTY67DvqpJdslfDP7NM/ZT8PaeqeBjrw06tZAkcwggJDMIIByKADAgECAhAJusXhvEAa2dRTlbw4GghUMAoGCCqGSM49BAMDMFIxJjAkBgNVBAMMHUFwcGxlIEFwcCBBdHRlc3RhdGlvbiBSb290IENBMRMwEQYDVQQKDApBcHBsZSBJbmMuMRMwEQYDVQQIDApDYWxpZm9ybmlhMB4XDTIwMDMxODE4Mzk1NVoXDTMwMDMxMzAwMDAwMFowTzEjMCEGA1UEAwwaQXBwbGUgQXBwIEF0dGVzdGF0aW9uIENBIDExEzARBgNVBAoMCkFwcGxlIEluYy4xEzARBgNVBAgMCkNhbGlmb3JuaWEwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAASuWzegd015sjWPQOfR8iYm8cJf7xeALeqzgmpZh0/40q0VJXiaomYEGRJItjy5ZwaemNNjvV43D7+gjjKegHOphed0bqNZovZvKdsyr0VeIRZY1WevniZ+smFNwhpmzpmjZjBkMBIGA1UdEwEB/wQIMAYBAf8CAQAwHwYDVR0jBBgwFoAUrJEQUzO9vmhB/6cMqeX66uXliqEwHQYDVR0OBBYEFD7jXRwEGanJtDH4hHTW4eFXcuObMA4GA1UdDwEB/wQEAwIBBjAKBggqhkjOPQQDAwNpADBmAjEAu76IjXONBQLPvP1mbQlXUDW81ocsP4QwSSYp7dH5FOh5mRya6LWu+NOoVDP3tg0GAjEAqzjt0MyB7QCkUsO6RPmTY2VT/swpfy60359evlpKyraZXEuCDfkEOG94B7tYlDm3Z3JlY2VpcHRZDkEwgAYJKoZIhvcNAQcCoIAwgAIBATEPMA0GCWCGSAFlAwQCAQUAMIAGCSqGSIb3DQEHAaCAJIAEggPoMYID+jAdAgECAgEBBBVWTlA1QTlTMjJWLjc2UjM4N01BVlowggLmAgEDAgEBBIIC3DCCAtgwggJeoAMCAQICBgGC05sgmTAKBggqhkjOPQQDAjBPMSMwIQYDVQQDDBpBcHBsZSBBcHAgQXR0ZXN0YXRpb24gQ0EgMTETMBEGA1UECgwKQXBwbGUgSW5jLjETMBEGA1UECAwKQ2FsaWZvcm5pYTAeFw0yMjA4MjQwNjA1MzVaFw0yMjA4MjcwNjA1MzVaMIGRMUkwRwYDVQQDDEBlMGIzMDkzYmZjMjQ0NzQ5M2E0YzgwZjY2MDE4MWJhOGFhMzFhODk0ZTg1N2NhMzZlMTIwOTAxYjNlN2UxMzA5MRowGAYDVQQLDBFBQUEgQ2VydGlmaWNhdGlvbjETMBEGA1UECgwKQXBwbGUgSW5jLjETMBEGA1UECAwKQ2FsaWZvcm5pYTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABLMD11RePEeSp0EYsDAGPs5nRsnmHdznwvhkN8pIVO4N8wtWtU0O+K1pHzKPk9/SFVJn4agWGgNWJSLgUFch0KCjgeIwgd8wDAYDVR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCBPAwbwYJKoZIhvdjZAgFBGIwYKQDAgEKv4kwAwIBAb+JMQMCAQC/iTIDAgEBv4kzAwIBAb+JNBcEFVZOUDVBOVMyMlYuNzZSMzg3TUFWWqUGBARza3Mgv4k2AwIBBb+JNwMCAQC/iTkDAgEAv4k6AwIBADAZBgkqhkiG92NkCAcEDDAKv4p4BgQEMTUuNTAzBgkqhkiG92NkCAIEJjAkoSIEIKWS15VGXk8g047rqp88eh43L5kApzwbMkzND5WPACpzMAoGCCqGSM49BAMCA2gAMGUCMQCGCFx5GUEkRquQt5Bw+8zUrz3n+TcgpJ0DrLSRLsp1yMWlDz5k0fvLAL6f8JXkxUECMC7Rd9n5rmeeB5wz162qJfwcRoIQe7JJNjrsO+qkl2yV8M/s0z9lPw9p6p4GOvDTqzAoAgEEAgEBBCArN2w8eB63198TiABUbeUjSesZzxxKjPq0P/KCzGRg5zBgAgEFAgEBBFhuZjJQYUUwUzZkTnJBdkpUbWExbEdnZHR0NXpVODg2c2J1cmh0NHRKZlZycHZwZWpkVmdSdlYrYmUrS0FlVEVpR0gzeUl5YmdwU0JnVUcwMHFvRDhZdz09MA4CAQYCAQEEBkFUVEVTVDAPAgEHAgEBBAdzYW5kYm94MCACAQwCAQEEGDIwMjItMDgtMjVUMDY6MDU6MzUuMjY0WjAgAgEVAgEBBBgyMAQWMjItMTEtMjNUMDY6MDU6MzUuMjY0WgAAAAAAAKCAMIIDrjCCA1SgAwIBAgIQCTm0vOkMw6GBZTY3L2ZxQTAKBggqhkjOPQQDAjB8MTAwLgYDVQQDDCdBcHBsZSBBcHBsaWNhdGlvbiBJbnRlZ3JhdGlvbiBDQSA1IC0gRzExJjAkBgNVBAsMHUFwcGxlIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MRMwEQYDVQQKDApBcHBsZSBJbmMuMQswCQYDVQQGEwJVUzAeFw0yMjA0MTkxMzMzMDNaFw0yMzA1MTkxMzMzMDJaMFoxNjA0BgNVBAMMLUFwcGxpY2F0aW9uIEF0dGVzdGF0aW9uIEZyYXVkIFJlY2VpcHQgU2lnbmluZzETMBEGA1UECgwKQXBwbGUgSW5jLjELMAkGA1UEBhMCVVMwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQ51PmqmxzERdZbphes8sCE7G8HCNWQFKDnbs897jmZqUxr+wFVEFVVZGzajiPgJgEUAtB+E7lUH9i01lfYLpN4o4IB2DCCAdQwDAYDVR0TAQH/BAIwADAfBgNVHSMEGDAWgBTZF/5LZ5A4S5L0287VV4AUC489yTBDBggrBgEFBQcBAQQ3MDUwMwYIKwYBBQUHMAGGJ2h0dHA6Ly9vY3NwLmFwcGxlLmNvbS9vY3NwMDMtYWFpY2E1ZzEwMTCCARwGA1UdIASCARMwggEPMIIBCwYJKoZIhvdjZAUBMIH9MIHDBggrBgEFBQcCAjCBtgyBs1JlbGlhbmNlIG9uIHRoaXMgY2VydGlmaWNhdGUgYnkgYW55IHBhcnR5IGFzc3VtZXMgYWNjZXB0YW5jZSBvZiB0aGUgdGhlbiBhcHBsaWNhYmxlIHN0YW5kYXJkIHRlcm1zIGFuZCBjb25kaXRpb25zIG9mIHVzZSwgY2VydGlmaWNhdGUgcG9saWN5IGFuZCBjZXJ0aWZpY2F0aW9uIHByYWN0aWNlIHN0YXRlbWVudHMuMDUGCCsGAQUFBwIBFilodHRwOi8vd3d3LmFwcGxlLmNvbS9jZXJ0aWZpY2F0ZWF1dGhvcml0eTAdBgNVHQ4EFgQU+2fTDb9zt5KmJl1IjSzBHZXic/gwDgYDVR0PAQH/BAQDAgeAMA8GCSqGSIb3Y2QMDwQCBQAwCgYIKoZIzj0EAwIDSAAwRQIhAJSQoGc3c+cveCk2diO43VHXyJoJ6rsA45xuRQsFWAvQAiBHNBor0TzAVKgKOqrMPMFFfABUUxjqM419bdX2CyuHLjCCAvkwggJ/oAMCAQICEFb7g9Qr/43DN5kjtVqubr0wCgYIKoZIzj0EAwMwZzEbMBkGA1UEAwwSQXBwbGUgUm9vdCBDQSAtIEczMSYwJAYDVQQLDB1BcHBsZSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTETMBEGA1UECgwKQXBwbGUgSW5jLjELMAkGA1UEBhMCVVMwHhcNMTkwMzIyMTc1MzMzWhcNMzQwMzIyMDAwMDAwWjB8MTAwLgYDVQQDDCdBcHBsZSBBcHBsaWNhdGlvbiBJbnRlZ3JhdGlvbiBDQSA1IC0gRzExJjAkBgNVBAsMHUFwcGxlIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MRMwEQYDVQQKDApBcHBsZSBJbmMuMQswCQYDVQQGEwJVUzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABJLOY719hrGrKAo7HOGv+wSUgJGs9jHfpssoNW9ES+Eh5VfdEo2NuoJ8lb5J+r4zyq7NBBnxL0Ml+vS+s8uDfrqjgfcwgfQwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBS7sN6hWDOImqSKmd6+veuv2sskqzBGBggrBgEFBQcBAQQ6MDgwNgYIKwYBBQUHMAGGKmh0dHA6Ly9vY3NwLmFwcGxlLmNvbS9vY3NwMDMtYXBwbGVyb290Y2FnMzA3BgNVHR8EMDAuMCygKqAohiZodHRwOi8vY3JsLmFwcGxlLmNvbS9hcHBsZXJvb3RjYWczLmNybDAdBgNVHQ4EFgQU2Rf+S2eQOEuS9NvO1VeAFAuPPckwDgYDVR0PAQH/BAQDAgEGMBAGCiqGSIb3Y2QGAgMEAgUAMAoGCCqGSM49BAMDA2gAMGUCMQCNb6afoeDk7FtOc4qSfz14U5iP9NofWB7DdUr+OKhMKoMaGqoNpmRt4bmT6NFVTO0CMGc7LLTh6DcHd8vV7HaoGjpVOz81asjF5pKw4WG+gElp5F8rqWzhEQKqzGHZOLdzSjCCAkMwggHJoAMCAQICCC3F/IjSxUuVMAoGCCqGSM49BAMDMGcxGzAZBgNVBAMMEkFwcGxlIFJvb3QgQ0EgLSBHMzEmMCQGA1UECwwdQXBwbGUgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkxEzARBgNVBAoMCkFwcGxlIEluYy4xCzAJBgNVBAYTAlVTMB4XDTE0MDQzMDE4MTkwNloXDTM5MDQzMDE4MTkwNlowZzEbMBkGA1UEAwwSQXBwbGUgUm9vdCBDQSAtIEczMSYwJAYDVQQLDB1BcHBsZSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTETMBEGA1UECgwKQXBwbGUgSW5jLjELMAkGA1UEBhMCVVMwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAASY6S89QHKk7ZMicoETHN0QlfHFo05x3BQW2Q7lpgUqd2R7X04407scRLV/9R+2MmJdyemEW08wTxFaAP1YWAyl9Q8sTQdHE3Xal5eXbzFc7SudeyA72LlU2V6ZpDpRCjGjQjBAMB0GA1UdDgQWBBS7sN6hWDOImqSKmd6+veuv2sskqzAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBBjAKBggqhkjOPQQDAwNoADBlAjEAg+nBxBZeGl00GNnt7/RsDgBGS7jfskYRxQ/95nqMoaZrzsID1Jz1k8Z0uGrfqiMVAjBtZooQytQN1E/NjUM+tIpjpTNu423aF7dkH8hTJvmIYnQ5Cxdby1GoDOgYA+eisigAADGB/jCB+wIBATCBkDB8MTAwLgYDVQQDDCdBcHBsZSBBcHBsaWNhdGlvbiBJbnRlZ3JhdGlvbiBDQSA1IC0gRzExJjAkBgNVBAsMHUFwcGxlIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MRMwEQYDVQQKDApBcHBsZSBJbmMuMQswCQYDVQQGEwJVUwIQCTm0vOkMw6GBZTY3L2ZxQTANBglghkgBZQMEAgEFADAKBggqhkjOPQQDAgRIMEYCIQDokFNbfS6jUo4lvLMuepiKRNc4ILQ9M+mylA/m4R/vDgIhANwjTwNMUT7h9pGBOZ1PTxmpFY3dimduPGa5fSZK477+AAAAAAAAaGF1dGhEYXRhWKRbmox+sLRL+Nu1jUz8mj38hvGvsVSnjKGVGaie7G/KmkAAAAAAYXBwYXR0ZXN0ZGV2ZWxvcAAg4LMJO/wkR0k6TID2YBgbqKoxqJToV8o24SCQGz5+EwmlAQIDJiABIVggswPXVF48R5KnQRiwMAY+zmdGyeYd3OfC+GQ3ykhU7g0iWCDzC1a1TQ74rWkfMo+T39IVUmfhqBYaA1YlIuBQVyHQoA==
```

Client data it was generated over is
`This is a test. This will need to be removed before merging.`

**Comment by Sebbs128** [comment]
Oh, I should also mention an issue you'll encounter due to a typo on Apple's side.

Apple's documentation says the `aaguid` will be `appattestdevelop` (converting to ASCII bytes then turning those into a `Guid` gives a value of `61707061-7474-7365-7464-6576656c6f70`). However, the value you'll see in the above sample is `61707061-7474-6573-7464-6576656c6f70` (which decodes to `appattsetdevelop`). I've already filed that with Apple.

**Comment by aseigler** [comment]
1. Never got around to doing that.  Theoretically we shouldn't keep getting new attestation types, it's kinda silly at this point.
2. Sucks that they won't document the formats or OIDs for that matter in a timely manner.  Also unfortunately, the custom `IMetadataService` will solve for you at most step 1 of this format verification steps.  Steps 2 - 4 are already done in the existing `apple` format verifier, the rest, 5 - 9 are completely new.
3. You can't touch the `clientDataJson`, we need the SHA256 hash of that to stay the same for steps 2 - 4 to work.  I suspect I will be able to find something.

> Oh, I should also mention an issue you'll encounter due to a typo on Apple's side.
> 
> Apple's documentation says the `aaguid` will be `appattestdevelop` (converting to ASCII bytes then turning those into a `Guid` gives a value of `61707061-7474-7365-7464-6576656c6f70`). However, the value you'll see in the above sample is `61707061-7474-6573-7464-6576656c6f70` (which decodes to `appattsetdevelop`). I've already filed that with Apple.

This is the kind of crap that drives me nuts.  That's no typo, friend.  Welcome to the wonderful world of having to pay attention to endianness.  Observe: https://dotnetfiddle.net/ZQcSqc  I wish they would just come out and say "the aaguid for dev is `"foo"` and the aaguid for prod is `"bar"`", or, you know, just the metadata service?  But no.

Stay tuned, I don't think this will actually be that difficult...

**Comment by Sebbs128** [comment]
1. I agree that _theoretically_ there shouldn't be new attestation types (or at least will be well advertised in an update to the spec). However, as with Apple App Attest, there will be some attestation types that developers occasionally need to support that aren't published in the spec. Having this extensibility point will hugely help developers that find themselves in that situation stick with this library.

I mentioned I might try to find the time to add that extensibility for `AttestationVerifier`. Would you consider accepting a PR if I can build that out? (It will at least remove that particular `// TODO:` in `VerifyAsync()` 😉 )

2. I'm glad to hear I can support the custom root via the `IMetadataService`. That will be a huge help.

3. I'll be interested to see what you might be able to find. Currently I've just used a `|` delimiter in the client data to allow distinguishing, but that of course requires both the app and server to know to do this (and of course wouldn't be suitable for a library).

Ok, that thing with the `aaguid` infuriates me as well now. Hard agree that Apple's documentation should explicitly say what the values are, especially as a) their docs don't mention favouring a particular endianness, and b) it only affects that pair of bytes.

**Comment by aseigler** [comment]
I meant the IMetadataService won't really help.  Check out what I've just pushed to https://github.com/passwordless-lib/fido2-net-lib/tree/feat-apple-appattest.

**Comment by aseigler** [comment]
> I mentioned I might try to find the time to add that extensibility for `AttestationVerifier`. Would you consider accepting a PR if I can build that out? (It will at least remove that particular `// TODO:` in `VerifyAsync()` 😉 )

We'd certainly entertain it if it seemed to add some value, for sure!
 
> Ok, that thing with the `aaguid` infuriates me as well now. Hard agree that Apple's documentation should explicitly say what the values are, especially as a) their docs don't mention favouring a particular endianness, and b) it only affects that pair of bytes.

The only reason it affects those pair of bytes is because there are so many a's and t's and p's and they just happen to line up such that only one of them actually matters.  In general, if you're working on Windows, it's little endian, everything else, big endian.  Nobody cares or pays any attention at all until you cross platforms, then it gets important.

**Comment by aseigler** [comment]
> Sorry, I meant it would help with step 1 for verifying x5c chain against a custom root (although, yes I understand that would be occurring outside the attestation verifier, and a user of your library would need to know to pass that custom IMetadataService to VerifyAsync()).

They wouldn't necessarily even need a custom IMetadataService, they could just add their custom metadata to a file based store which is supported by the library and required by the server spec and conformance tests.

> > The only reason it affects those pair of bytes is because there are so many a's and t's and p's and they just happen to line up such that only one of them actually matters.
> 
> Yeah that became apparent looking at your fiddle link, very (un)fortunate coincidence those lined up. It's been a while since I've had to deal with endianness, but I don't understand why the "develop" part (last 7 bytes) wouldn't be affected?

Has to do with how guid is defined.  See https://www.rfc-editor.org/rfc/rfc4122.html.
 
> On that note, seeing as .NET is crossplatform, should you consider adding a check of `BitConverter.IsLittleEndian` before calling your `FromBigEndian()` method in case someone is running this on macOS or Linux?

No need.  The cert is built and encoded on the server, it will always be big endian no matter what the client platform is.

> ETA: I'll be doing testing of my applications that lead me down this whole path over the next few days, so I'll be able to confirm the `prodAaguid` value for you.

Sweet.  I can't tell by the docs if they mean it the way I have it written or if they mean pad everything else out in the aaguid after the last 't' with zeroes.  Neither option really makes any sense at all, but I have no idea so I am guessing for now.

**Comment by Sebbs128** [comment]
> I can't tell by the docs if they mean it the way I have it written or if they mean pad everything else out in the aaguid after the last 't' with zeroes.

My interpretation was that they were padded with zero bytes (ie. null characters or `"\0"`), but again I'll let you know :)

**Comment by aseigler** [comment]
> > I can't tell by the docs if they mean it the way I have it written or if they mean pad everything else out in the aaguid after the last 't' with zeroes.
> 
> My interpretation was that they were padded with zero bytes (ie. null characters or `"\0"`), but again I'll let you know :)

I suspect you're right, but it's easier for me to hope that my first guess is the right one and if not fix it later before merge.

**Comment by Sebbs128** [comment]
>> On that note, seeing as .NET is crossplatform, should you consider adding a check of BitConverter.IsLittleEndian before calling your FromBigEndian() method in case someone is running this on macOS or Linux?

> No need. The cert is built and encoded on the server, it will always be big endian no matter what the client platform is.

I was more thinking that when you're ASCII encoding the string "appattestdevelop" in AppleAppAttest.cs won't the endianness of the machine Fido2NetLib is running on come into play?

(I also would have thought Apple's infrastructure is running on Intel servers, which would be little-endian. Unless either they've moved to M1 or M2-based machines or the AttestedCredentialData is generated on-device, even if just when debugging, although those would both mean those ARM CPUs are operating in big-endian mode. I guess I can only speculate though).

**Comment by aseigler** [comment]
Well, we have a unit test already for this that should run cross platform no problem...

**Comment by Sebbs128** [comment]
> > > I can't tell by the docs if they mean it the way I have it written or if they mean pad everything else out in the aaguid after the last 't' with zeroes.
> > 
> > 
> > My interpretation was that they were padded with zero bytes (ie. null characters or `"\0"`), but again I'll let you know :)
> 
> I suspect you're right, but it's easier for me to hope that my first guess is the right one and if not fix it later before merge.

Hey aseigler. I've just been able to get a production App Attest object sent from a release build of our app. I can confirm the aaguid is padded with 0 bytes (ie. null characters). And of course, those bytes swapped due to endianness.

**Comment by aseigler** [comment]
> Hey aseigler. I've just been able to get a production App Attest object sent from a release build of our app. I can confirm the aaguid is padded with 0 bytes (ie. null characters). And of course, those bytes swapped due to endianness.

So  `61707061-7474-6573-7400-000000000000` is correct then?

**Comment by Sebbs128** [comment]
Yes, that's correct.
