### ISSUE TITLE
Support "hybrid" transport type 

### ISSUE THREAD

**Issue by ninamwa** [passwordless-lib/fido2-net-lib#325]
The transport type "hybrid" is now a part of the webauthn spec, so would be great if this was supported in the AuthenticatorTransport enum type! :-)

**Comment by abergs** [comment]
Note: It's not in the published W3C spec currently, but in the editor draft: https://w3c.github.io/webauthn/#dom-authenticatortransport-hybrid

**Comment by merijndejonge** [comment]
It now is: https://www.w3.org/TR/webauthn-3/#enum-transport
Can you please add?

**Comment by abergs** [comment]
@merijndejonge its already merged.

**Comment by merijndejonge** [comment]
Thanks for the lightning-fast response! 
I don't see a new nuget version, though. Am I right?

**Comment by abergs** [comment]
We're up to beta.13 I think, and there will be a couple more of them. However, while there are some more breaking api changes to come, they are mostly style related and beta 13 should be stable to run in prod.

**Comment by merijndejonge** [comment]
I noticed that there are quite a number of breaking changes in the beta. Is there documentation available about how to migrate?

**Comment by abergs** [comment]
No, unfortunately not. At least not for now.
