### ISSUE TITLE
On .Net 6, the System.Json.Text serializer now seems to choke on the return value in the MakeAssertion function.

### ISSUE THREAD

**Issue by abergs** [passwordless-lib/fido2-net-lib#328]
It throws this exception:
"Serialization and deserialization of 'System.IntPtr' instances are not supported. Path: $.Result.AttestationCertificate.Handle."

The problem can also be recreated in your current master branch if you register a new credential in the demo app under Custom with Direct attestation

Originally posted in #305 https://github.com/passwordless-lib/fido2-net-lib/issues/305#issuecomment-1261844396

**Comment by abergs** [comment]
The root problem is quite self explanatory. System.Json.Text does not support serialization of System.IntPtr.

The CredentialMakeResult contains a `X509Certificate2` which contains the System.IntPtr as the `Handle` property.

There are many ways to solve this problems:
1. Not serialize the  `X509Certificate2` (e.g. setting `AttestationCertificate` it to null, before serialization)
2. Convert the entire Result object to a custom DTO that has the properties to are interested in
3. Use a [custom converter](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/converters-how-to?pivots=dotnet-6-0)

Thanks for the report. I have fixed the problem in our Demo site. @m-gug

**Comment by dIeGoLi** [comment]
Maybe it would make sense to add [JsonIgnore] attribute this property. That way we do not have to set the property to null manually.
