### ISSUE TITLE
VerifyAsync accepts Fmt = "none" even when AttestationConveyancePreference was "direct"

### ISSUE THREAD

**Issue by juanmgutierrez** [passwordless-lib/fido2-net-lib#335]
Method `VerifyAsync` from `AuthenticatorAttestationResponse` doesn't check which `Attestation` was inside `originalOptions`.
It uses an `AttestationVerifier` selected depending on what was in the request (`AttestationObject.Fmt`):

```
AttestationVerifier verifier = AttestationObject.Fmt switch
{
    // TODO: Better way to build these mappings?
    "none" => new None(),                           // https://www.w3.org/TR/webauthn/#none-attestation
    "tpm" => new Tpm(),                             // https://www.w3.org/TR/webauthn/#tpm-attestation
    "android-key" => new AndroidKey(),              // https://www.w3.org/TR/webauthn/#android-key-attestation
    "android-safetynet" => new AndroidSafetyNet(),  // https://www.w3.org/TR/webauthn/#android-safetynet-attestation
    "fido-u2f" => new FidoU2f(),                    // https://www.w3.org/TR/webauthn/#fido-u2f-attestation
    "packed" => new Packed(),                       // https://www.w3.org/TR/webauthn/#packed-attestation
    "apple" => new Apple(),                         // https://www.w3.org/TR/webauthn/#apple-anonymous-attestation
    _ => throw new Fido2VerificationException("Missing or unknown attestation type")
};
```

The problem with this is that if we requested attestation by returning **"direct"** as the `AttestationConveyancePreference`, then we are not checking that in that case `AttestationObject.Fmt` was different than **"none"**.

I'm right with my analysis or am I missing something?

Thanks for your time!

**Comment by aseigler** [comment]
You're confusing different places where "none" is used. See https://www.w3.org/TR/webauthn/#sctn-registering-a-new-credential. 

AttestationConveyancePreference comes into play in steps 1/2, the attestation statement format (fmt) is evaluated first at step 18. They are different things entirely.

**Comment by juanmgutierrez** [comment]
Yes, but what if someone in the middle pass "none" into the authenticator when RP sent "direct"?
If I'm not missunderstanding, point 21 talks about verifying that:

> 21. Assess the attestation trustworthiness using the outputs of the [verification procedure](https://www.w3.org/TR/webauthn/#verification-procedure) in step 19, as follows:
> 
> - **If [no attestation](https://www.w3.org/TR/webauthn/#none) was provided, verify that [None](https://www.w3.org/TR/webauthn/#none) attestation is acceptable under [Relying Party](https://www.w3.org/TR/webauthn/#relying-party) policy.**
> - If [self attestation](https://www.w3.org/TR/webauthn/#self-attestation) was used, verify that [self attestation](https://www.w3.org/TR/webauthn/#self-attestation) is acceptable under [Relying Party](https://www.w3.org/TR/webauthn/#relying-party) policy.
> - Otherwise, use the X.509 certificates returned as the [attestation trust path](https://www.w3.org/TR/webauthn/#attestation-trust-path) from the [verification procedure](https://www.w3.org/TR/webauthn/#verification-procedure) to verify that the attestation public key either correctly chains up to an acceptable root certificate, or is itself an acceptable certificate (i.e., it and the root certificate obtained in Step 20 may be the same).

**Comment by aseigler** [comment]
If the attestation didn't have the properties necessarily by the RP policy, the RP can refuse the registration.  In step 21, that's talking about the attestation statement format, where it says self, that's actually a subtype of the "packed" format.

**Comment by juanmgutierrez** [comment]
As I understand, in these particular two lines:

> Assess the attestation trustworthiness using the outputs of the [verification procedure](https://www.w3.org/TR/webauthn/#verification-procedure) in step 19, as follows:
> - If [no attestation](https://www.w3.org/TR/webauthn/#none) was provided, verify that [None](https://www.w3.org/TR/webauthn/#none) attestation is acceptable under [Relying Party](https://www.w3.org/TR/webauthn/#relying-party) policy.

Documentation is not saying that is part of the verification to check whether it was or not valid to have no attestation?
And in that case, wouldn't be better to check before creating `new None()` as `AttestationVerifier `, that `originalOptions.Attestation` wasn't `Direct`?

**Comment by aseigler** [comment]
It's not the same thing.  The `options.Attestation` tells the call to `navigator.credentials.create()` to tell the authenticator to make a credential with those characteristics, that's step 2.  Everything after the credential has been made, past step 3 is checking the result of that call to first determine if it meets spec, and second to make sure it meets RP policy.

**Comment by juanmgutierrez** [comment]
But, what if someone in the middle changed the original "direct" into a "none" string before it reachs the authenticator? Then if we look at the response and says fmt="none", shouldn't we say: "Wait a moment, I asked you to have attestation", instead of letting it pass without attestation validation?

**Comment by aseigler** [comment]
The attStmt.fmt "none" has nothing to do with the options.attestation "none".  The RP in steps 3 - 21 checks the result to see if it matches spec and policy, if anything is amiss, the registration should be failed.

**Comment by juanmgutierrez** [comment]
Ok, thanks for the patience clarifying this issue to me. I'm gonna close it, and go direct to read the whole [W3 documentation](https://www.w3.org/TR/webauthn-2/). Thanks again!

**Comment by aseigler** [comment]
Check out https://w3c.github.io/webauthn/#dom-publickeycredentialcreationoptions-attestationformats.  It's been made a bit more obvious in this draft of the next version of the spec.
