### ISSUE TITLE
[The input is not a valid Base-64 string as it contains a non-base 64 character]

### ISSUE THREAD

**Issue by anandsb84** [passwordless-lib/fido2-net-lib#336]
Hi

For me these are the  part of AuthenticatorAssertionRawResponse clientResponse 
"Id": "CPLzBh1geg1gyTG7mupMq63L7dzFCzu0TzK6iA7Vat8"
"RawId":"CPLzBh1geg1gyTG7mupMq63L7dzFCzu0TzK6iA7Vat8="
but clientResponse.id gives error saying..
[The input is not a valid Base-64 string as it contains a non-base 64 character]
Can you please help why am i getting these clientResponse and what could be done to make it right

**Comment by abergs** [comment]
I would need more information about the exception to understand where and when that problems arises, but:
**We use Base64Url encoding throughout the library**, which is slightly different from Base64 and often causes errors like then one you are receiving.

**Comment by abergs** [comment]
@anandsb84 Were you able to resolve this?

**Comment by mlh758** [comment]
[These functions](https://github.com/passwordless-lib/fido2-net-lib/blob/24a2acebbda79bda561e72e96fb10623cd470bd2/Demo/wwwroot/js/helpers.js) in the demo app are pretty helpful. Like @abergs said `Base64Url` encoding is the default JSON option for a lot of the binary types in this library and `atob` / `btoa` don't play well with it directly.
