### ISSUE TITLE
Windows Hello not being recognized for Authentication

### ISSUE THREAD

**Issue by kile-lindgren** [passwordless-lib/fido2-net-lib#339]
I'm having an issue with Windows Hello not being recognized when doing passwordless authentication.  I can register with Windows Hello, but when I then try to authenticate I get the message from windows to "Insert your security key into the USB port."

Windows 10, Running Chrome 107.  But I get the same issue in Edge as well.

Not sure what adjustments that I need to make to get this to allow Windows Hello for both.

**Comment by abergs** [comment]
What AuthenticatorAttachment are you using? If you are using `cross-platform` it would tell the browser to prefer usb/security keys

**Comment by kile-lindgren** [comment]
I'm specifying platform for authenticator attachment.

let attestation_type = "none";
let authenticator_attachment = "platform";
let user_verification = "preferred";
let require_resident_key = "false";

**Comment by iamcarbon** [comment]
Hi @kile-lindgren  -- did you figure this out?

**Comment by kile-lindgren** [comment]
I figured this out.  I was serializing the object wrong into my persistent data store, as such when trying to pull the records out, it didn't match any on the device and was prompting for the security key.  When I fixed the serialization, it worked correctly.
