### ISSUE TITLE
Will the 2.x branch still receive updates in the future?

### ISSUE THREAD

**Issue by lrolvink** [passwordless-lib/fido2-net-lib#349]
Hi,

Hopefully I can ask my question in here. The current version is 3.x that also drop support for older .net runtimes. Will the 2.x version (after 2.0.2) still receive updates in the near future or is this become deprecated?

**Comment by abergs** [comment]
@lrolvink Hello Lorenzo, currently there are no plans to maintain the 2.0.2 branch.

If there is large community interest, I am open to accepting PRs to address issues in a 2.x branch but it will be based on the amount of time & energy available.
