### ISSUE TITLE
Remove the registered users or Reduce it to a single user

### ISSUE THREAD

**Issue by anandsb84** [passwordless-lib/fido2-net-lib#366]
Hi 
Team, 
I have used the sample given for passwordless-lib.
And i am having a 
Hyper FIDO Mini Pro U2F FIDO2 HOTP
![image](https://user-images.githubusercontent.com/48145761/213392059-70bd5be5-d24f-4c8e-b8ae-bae15818ce67.png)

And while trying to use the sample for registration in usernameless, the number of times we register in it, 
the more the number of users are shown up in  list..
![image](https://user-images.githubusercontent.com/48145761/213392278-f64b4033-f206-4b1a-a378-7021f532a176.png)

Is there a way to remove the registered users??
Also can we reduce the registered user to be "one" user for a fido usb??
Please help me with the solution.

**Comment by abergs** [comment]
Well there are a couple of things to answer here.

1) Removing keys is not something *we* can do. Each platform has their own Management tool to manipulate data stored on the Security Key (e.g. Yubicos Yubikey Manager etc). Different for each brand of Security Key.

2) Not really. There are a couple of different ways to work around it (the demo automatically creates a new user everytime, you might want to do this differently, e.g. trying to do a login before you register) -- but for privacy reasons, you can't get a unique fingerprint for a security key.
