### ISSUE TITLE
How to store and fetch CredentialCreateOptions 

### ISSUE THREAD

**Issue by merijndejonge** [passwordless-lib/fido2-net-lib#367]
Hi,
In the demo the CredentialCreateOptions are stored in the http session. If I'm not mistaken, this will not work with more than one registration process in parallel. It also doesn't work with multiple backend instances (e.g., in a cloud environment). 

What is the appropriate method to fetch an CredentialCreateOptions object? There is no ID property in CredentialCreateOptions that I can use. I could perhaps use CredentialCreateOptions.Challenge. However, AuthenticatorAttestationRawResponse does not contain a Challenge. Meaning I first have to call AuthenticatorAttestationResponse.Parse() but then parsing is happening twice because it is also done in MakeNewCredentialAsync.

Any advice would be great!

**Comment by abergs** [comment]
A HTTP Session is unique for each session (user/visitor) so it will work well with multiple registration in parallel.

Regarding cloud/mulitple backends: Sessions are supported in cloud environment, but you might need to add support for distribution (https://learn.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-7.0). Adding support for distribution comes in a all shapes and sizes, e.g. storing session state in a database or redis or using Stick Sessions (ARR) that's built into Azure.
You can serialize a CredentialCreateOptions, store it in database with some ID and fetch it back up.

If you are looking for **an easier solution** that solves these problems for you, I would look into [passwordless.dev](https://passwordless.dev)(which I'm also behind). This library is an excellent engine if you know how to use it. The passwordless.dev service builds on top of it to make it very easy to get started and not having to worry about the kind of issues you are having.
