### ISSUE TITLE
Publish for multiple targets

### ISSUE THREAD

**Issue by Regenhardt** [passwordless-lib/fido2-net-lib#380]
Currently, `$SupportedTargetFrameworks` only contains net6.0 - some other files do however contain logic that points to this libs having been available for other framework version too, like net5 or net472 (there are checks failing the build for net46x).  

So to offer this lib for older applications but also be able to use compiler features of newer versions like source generation (see e.g. https://github.com/dotnet/runtime/issues/81709), can we add other targets to the `$SupportedTargetFrameworks`, or would that jeopardize other features?

**Comment by iamcarbon** [comment]
@Regenhardt .NET5.0 is out of service and the library dropped support for the .NET Framework in the 3.0 release cycle. Since since, the library has utilized many features to improve the security, performance, and maintainability of the codebase from .NET CORE (.NET).

Are there any specific files reference .NET Framework? These should be removed or updated.

**Comment by Regenhardt** [comment]
[fido2.targets](https://github.com/passwordless-lib/fido2-net-lib/blob/master/Src/Fido2/build/fido2.targets) seems to only exist to tell netstandard users that the lib doesn't work with net46x, as is this doc: https://github.com/passwordless-lib/fido2-net-lib/blob/master/Documentation/NET46X.md .  
There was an issue asking how to use this in .net48 so I thought it would be nice.

Should i make a PR deleting those two files then?

**Comment by Regenhardt** [comment]
Also what about adding net7 to the targets to get those new source generation features for people already using net7?

**Comment by Regenhardt** [comment]
When the frontend lib is merged, it includes a serializer context that works in a net7 frontend too. I just tried setting the applications (Blazor server + client) to net7 keeping the libs at net6 and it worked without any other modifications. You can see the frontend serializer used [here](https://github.com/passwordless-lib/fido2-net-lib/pull/379/files#diff-56820079f65bbc55deac72ba74a0961447b51bc7ebdd3965e5fdae34b62e718e), initialized in line 18 and used e.g. in line 78.
