### ISSUE TITLE
Fido2 Assertion Fails:  The operation either timed out or was not allowed

### ISSUE THREAD

**Issue by TravisKool** [passwordless-lib/fido2-net-lib#382]
I am using Blazor WASM .net 7 and have success with attestation / registration. I am testing using https://localhost . This issue happens on both Chrome and firefox latest versions when trying to "Login" and get the credentials..

I am successfully creating assertion options using this library, but when I call into the js method that calls navigator.credentials.get, it is failing. Prior to seeing the console exception, the authenticator pops up and seems to successfully scan my face (as it did during registration), then it pauses for 5 seconds and throws the jsexception seen below. Any thoughts?

Input captured in c# prior to the invoke. Note: I just used jsonConvert to obtain this output, so it's not base64url
<img width="977" alt="image" src="https://user-images.githubusercontent.com/5742961/222967389-c43e9a15-e3a0-4ef7-a9a3-c62aaea79c6d.png">

invoke which seems to be working as the windows hello shows up
<img width="780" alt="image" src="https://user-images.githubusercontent.com/5742961/222967692-5fc2871c-3613-40a5-899a-01afed174192.png">

The js used to invoke the navigator
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/5742961/222967652-17ac0811-81fa-42fe-9f01-fecdb03468a6.png">

the error...
`Microsoft.JSInterop.JSException: The operation either timed out or was not allowed. See: https://www.w3.org/TR/webauthn-2/#sctn-privacy-considerations-client.
blazor.webassembly.js:1 undefined
blazor.webassembly.js:1    at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Fido2NetLib.AuthenticatorAssertionRawResponse, Fido2.Models, Version=3.0.1.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
blazor.webassembly.js:1    at WebAuthn.VerifyAsync(AssertionOptions options) in C:\git\EventFinder\Access.Web\Authentication\WebAuthn.cs:line 44
blazor.webassembly.js:1    at AuthenticationAccess.LoginAsync(String email) in C:\git\EventFinder\Access.Web\Authentication\AuthenticationAccess.cs:line 111

**Comment by nicowitteman** [comment]
Does it literally have `"Ty…MBAAE=",`?

**Comment by TravisKool** [comment]
Hey Nico, I am not sure what that was, I re-did the test and used screenshots and updated my original comment. That does not appear to be there anymore -> still have the error.

**Comment by Regenhardt** [comment]
Can you maybe make a public repo with minimal code to reproduce this error? 

Also to debug this step a bit more I did the following:  
1) Add `console.log('options:', options);` right before the credentials.get call  
2) Add `console.log('response:', retval);` right before returning retval

This way, you can inspect the whole object in your browser console without potentially losing information through serialization.

**Comment by Regenhardt** [comment]
@TravisKool have you found a solution? Otherwise, can you try using .NET 8 and directly use the Fido2.BlazorWebAssembly project for now?

**Comment by schotime** [comment]
I just tried this today and ran into the same thing.

```cs
    [HttpPost]
    [Route("api/passkey/register/initiate")]
    public async Task<IActionResult> InitiateRegistration()
    {
        var fido2User = new Fido2User
        {
            Id = Encoding.ASCII.GetBytes(Guid.NewGuid().ToString()),
            Name = "Name",
            DisplayName = "Name",
        };

        var fido2Options = _fido2.RequestNewCredential(fido2User, [], AuthenticatorSelection.Default, AttestationConveyancePreference.None);

        return Json(fido2Options);
    }
```

```ts
    import { startRegistration } from "@simplewebauthn/browser";

    async registerPasskey() {
        const options = await fetch('/api/passkey/register/initiate', {
            method: 'POST',
            body: '{}',
            headers: { 'Content-Type': 'application/json' },
        }).then(res => res.json());

        console.log(options);

        const attResp = await startRegistration(options);

        console.log(attResp);

        await fetch('/api/passkey/register/complete', {
            method: 'POST',
            body: JSON.stringify(attResp),
            headers: { 'Content-Type': 'application/json' },
        });
    }
```

Output of first console.log

```json
{
    "rp": {
        "id": "localhost",
        "name": "ucb",
        "icon": null
    },
    "user": {
        "name": "name",
        "id": "YmJiMWYxNGItZTg1Ny00MWFkLWFhZDUtZWRmNTE5M2MzZGUz",
        "displayName": "name"
    },
    "challenge": "zfzYgGoUdt0KkMHT6KYPqA==",
    "pubKeyCredParams": [
        {
            "type": "public-key",
            "alg": "ES256"
        },
        {
            "type": "public-key",
            "alg": "RS256"
        },
        {
            "type": "public-key",
            "alg": "PS256"
        },
        {
            "type": "public-key",
            "alg": "ES384"
        },
        {
            "type": "public-key",
            "alg": "RS384"
        },
        {
            "type": "public-key",
            "alg": "PS384"
        },
        {
            "type": "public-key",
            "alg": "ES512"
        },
        {
            "type": "public-key",
            "alg": "RS512"
        },
        {
            "type": "public-key",
            "alg": "PS512"
        },
        {
            "type": "public-key",
            "alg": "EdDSA"
        }
    ],
    "timeout": 60000,
    "attestation": "none",
    "authenticatorSelection": {
        "authenticatorAttachment": null",
        "requireResidentKey": false,
        "userVerification": "preferred"
    },
    "excludeCredentials": [],
    "extensions": null,
    "status": "ok",
    "errorMessage": ""
}
```

But it throws in the startRegistration()

```
Uncaught (in promise) NotAllowedError: The operation either timed out or was not allowed. See: https://www.w3.org/TR/webauthn-2/#sctn-privacy-considerations-client.
    at identifyRegistrationError (index.js:90:16)
    at startRegistration (index.js:200:15)   
```

**Comment by Regenhardt** [comment]
@schotime does windows hello pop up and authenticate you before the exception? Does the sample/demo project work for you locally? 

I see you call `startRegistration` with the options from the server there, which is from a library I haven't tried yet. Try replacing that function call with the following, which includes a few necessary conversions the browser wants:

```ts
export async function createCreds(options: PublicKeyCredentialCreationOptions) {
    if (typeof options.challenge === 'string')
        options.challenge = fromBase64Url(options.challenge);
    if (typeof options.user.id === 'string')
        options.user.id = fromBase64Url(options.user.id);
    if (options.rp.id === null)
        options.rp.id = undefined;
    for (let cred of options.excludeCredentials) {
        if (typeof cred.id === 'string')
            cred.id = fromBase64Url(cred.id);
    }
    var newCreds = await navigator.credentials.create({ publicKey: options }) as PublicKeyCredential;
    const response = newCreds.response as AuthenticatorAttestationResponse;
    const retval = {
        id: base64StringToUrl(newCreds.id),
        rawId: toBase64Url(newCreds.rawId),
        type: newCreds.type,
        clientExtensionResults: newCreds.getClientExtensionResults(),
        response: {
            attestationObject: toBase64Url(response.attestationObject),
            clientDataJSON: toBase64Url(response.clientDataJSON),
            transports: response.getTransports ? response.getTransports() : []
        }
    };
    return retval;
}
```

([Source](https://github.com/passwordless-lib/fido2-net-lib/blob/master/Src/Fido2.BlazorWebAssembly/wwwroot/js/WebAuthn.ts))

If that doesn't work, can you make a public repo so we can reproduce your error locally?

**Comment by schotime** [comment]
So this also returned the same error, and didn't popup the hello prompt.

I tried both on Chrome and actually the error was slightly different. 
Something about no suitable algorithm found.

**Comment by Regenhardt** [comment]
When the demo project doesn't work, it's something about your setup. Do you have windows hello set up, with fingerprint or face id? Pretty sure pin login is not included in the options of the demo project, so that alone won't work. For that, you'd have to add another algorithm I think, although the point of the lib is of course to use biometrics and not a pin.

**Comment by schotime** [comment]
That could be it. This is on a desktop with only PIN available. I just figured it would work as I've used that on other sites. I guess not?

**Comment by Regenhardt** [comment]
Exactly, other sites have an additional algorithm in the list that allows PIN authentication. The demo app is supposed to demonstrate fingerprint or face id authentication, so for PIN login you have to find out which algorithm that is and add it to the options provided to the browser.

**Comment by abergs** [comment]
Is there anything we should adress here?
