### ISSUE TITLE
Automatically add https scheme to fully qualify origin

### ISSUE THREAD

**Issue by Regenhardt** [passwordless-lib/fido2-net-lib#385]
The function ToFullyQualifiedOrigin removes any route beyond the authority (host+port), but doesn't add a scheme if there isn't one in the input string. Not sure about how full qualification is defined exactly, but it doesn't feel fully qualified if it doesn't have the scheme, which the FullyQualifiedOrigins property that uses this function expects to have set.

This leads to this being obligatory:  

```
    options.ServerDomain = origin;
    options.Origins = new HashSet<string> { $"https://{origin}" };
```

Can we add `?? "https://` in there to make sure there is something there if it isn't present in the input?  
Going with https here since this is the general default.

**Comment by aseigler** [comment]
I think that will break Android apps if I remember correctly.

**Comment by Regenhardt** [comment]
Do you know of an open source android app I could look at? I'd like to know how the whole RpId thing works in android, since the app doesn't have an origin the server could match the RpId to.

**Comment by aseigler** [comment]
Not off the top of my head, but this came up in #237.

**Comment by Regenhardt** [comment]
OK I see, never mind then, thanks for checking.
