### ISSUE TITLE
hello windows and webauthn authetification

### ISSUE THREAD

**Issue by MimiaBena** [passwordless-lib/fido2-net-lib#386]
Hello,

I'm using a navigator.credentials.get({publikKey}) to trigger the webauthn but it take a lot lot of time to trigger) . I'm on window11 (HELLO WINDOWS authenticator). 

Also when i test the demo of webauthn (https://webauthn.io/). It take a lot time juste for authentification. 

any idea please!

**Comment by MimiaBena** [comment]
Yes, i'm using my laptop with power mode full but i have the same problem

**Comment by abergs** [comment]
I haven't seen any full solution to this yet. Make sure to keep your windows updated and all the drivers -- hopefully they can resolve it. Closing since we can't do anything about it.
