### ISSUE TITLE
webauthn and screen lock opera browser

### ISSUE THREAD

**Issue by MimiaBena** [passwordless-lib/fido2-net-lib#391]
Hello,
I'm looking to authenticate by finger print. on chrome all is good but on Opera, i have an error

 `The specified `userVerification` requirement cannot be fulfilled by this device unless the device is secured with a screen lock.`

I add some extensions with uvi, uvm but i had the same error.

`authenticatorSelection: {
    authenticatorAttachment: "platform"
},`

`extensions : {
    uvi: true,
    uvm: true
},`

Any help please.

Thanks

**Comment by Regenhardt** [comment]
Do you have the screen lock activated and secured with your fingerprint?
