### ISSUE TITLE
adding a origin to Origins directly should throw a error

### ISSUE THREAD

**Issue by Kees-van-Beilen** [passwordless-lib/fido2-net-lib#392]
It should be made clear that this code doesn't work. With an error/warning message when setting options.Origins to an empty set. Or the error: "Fully qualified origin {} of {} not equal to fully qualified original origin {,} ({})" could be elaborated to remind the user of checking how the HashSet had been inited 
```
Services.AddFido2(options=>{
        //...
        options.Origins = new HashSet<string>();
        options.Origins.Add("http://localhost:5091");
       //...
})
```

**Comment by abergs** [comment]
I agree that this is a confusing behavior. I would welcome a PR to improve this.

**Comment by Regenhardt** [comment]
We could just change the type from ISet to IReadOnlySet, stopping users from changing the origins after setting them and only allowing them to assign a new set. This way, you can see it immediately when implementing it instead of having to check the exception at runtime.

**Comment by abergs** [comment]
@Regenhardt Yeah I think that could work since HashSet derives from IReadOnlySet
