### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by nicowitteman** [passwordless-lib/fido2-net-lib#394]
I was wondering if you might consider making the warning and error messages translatable to other languages than English.

**Comment by abergs** [comment]
I'm open to discuss the idea - but lack experience in how to effectively deploy and scale translations in a open source library.

What is your use case?

**Comment by abergs** [comment]
We've been doing a drive to standardize the error messages. So if your use case is to relay the error to the end user, I think you should catch it and translate/customize it in your app.
