### ISSUE TITLE
[Feature]: support wildcard in origins configuration

### ISSUE THREAD

**Issue by AkiraVoid** [passwordless-lib/fido2-net-lib#395]
This library currently check the origin of authenticator response to see whether if it is made by a trusted origin which is configured in Origins property on startup. I will say it makes debugging and using very difficult, as we may have the need of making it available from many origins, in runtime and incrementally. So I am wondering could we have a feature like allowing wildcard usage in origins configuration?

**Comment by Regenhardt** [comment]
You could create a new config object on each call, setting the origin from your controller if it fits your desired pattern, then use that config object to instantiate a new service. Wildcard would be easier indeed, but this would work and I don't know enough about security stuff or specifications to assess actually adding it to the library.

**Comment by AkiraVoid** [comment]
May you could add a flag to disable origins check in development environment?
