### ISSUE TITLE
Status of Project

### ISSUE THREAD

**Issue by dgioulakis** [passwordless-lib/fido2-net-lib#396]
Last nuget release was 10 months ago. There are several open PRs. I'm trying to evaluate whether this is a stable library our organization can seriously adopt or should depend on. Are there any plans to create more defined milestones and release cadences? For an enterprise use-case, should we perhaps create our own fork to maintain and contribute to? It's concerning that there seems to be no pre-release packages or insight into when a next version might be released.

All the work the authors of this library have done so far is greatly appreciated and impactful. I'm merely just looking at this from a perspective of due diligence.

**Comment by abergs** [comment]
Hey @dgioulakis,
We are indeed alive and well. The release of 4.0 as been delayed mostly due to #356.

I will be looking into putting more energy into this library as part of my work at Bitwarden and [Passwordless.dev](https://passwordless.dev)

**Comment by aseigler** [comment]
#356 is marked ready for review, if everyone is good with it as is we can merge.

**Comment by dgioulakis** [comment]
That's great to hear! Thanks for the information @abergs @aseigler
