### ISSUE TITLE
Enterprise Attestation

### ISSUE THREAD

**Issue by mangoplane** [passwordless-lib/fido2-net-lib#398]
As the title reads, I'm researching how to do enterprise attestation where the the devices serial number is attested to reduce the incidence of spam account creation.

Among other settings, it requires `enterprise` as the value for [credentialCreationData.attestationConveyancePreferenceOption](https://www.w3.org/TR/webauthn-2/#credentialcreationdata-attestationconveyancepreferenceoption) during registration.

I appreciate any insight from the community, and it may turn out this is supported by all good webauthn RP and clients by default. I'm not sure.

**Comment by abergs** [comment]
@aseigler might have more intel on this? :)

**Comment by aseigler** [comment]
I added `enterprise` as an option in #277.  I don't think there is anything defined for an RP to do with it, it's more for the client to tell the user that the registration is going to supply the RP with the make/model/serial number of the authenticator, and that the authenticator supply the serial number in the attestation statement so the RP can ensure the user is registering the device with the serial number that was issued to that user.

I've never actually seen this kind of flow in action with a WebAuthn server, but this is a common scenario with smart card deployments.

**Comment by abergs** [comment]
@mangoplane Please file that as a different issue here on github so that we can track it.

**Comment by abergs** [comment]
Merged in #410
