### ISSUE TITLE
NuGet Package is out of date

### ISSUE THREAD

**Issue by bugnuker** [passwordless-lib/fido2-net-lib#400]
The NuGet package is out of date and does not include some PRs, specifically this one: https://github.com/passwordless-lib/fido2-net-lib/issues/310

The package was last built in September 2022 and the PR in question is from Oct 15th, 2022. 

The current demos in the source code do not work with the NuGet package due to the outdated ResidentKeyRequirement change in the NuGet package.

Recommend updating pipelines to build/publish nuget packages.

**Comment by bugnuker** [comment]
Any plans to update the Nuget package? Has this been abandoned?

**Comment by abergs** [comment]
I would love a PR that adds a pr that publishes a pre-release version of the Nuget package. Don't know if we should publish to nuget/github repo, but that would be great.

FYI A nuget package release is upcoming. Keeping this ticket open for transparency until it's released.

**Comment by abergs** [comment]
A 4.0.0-beta1 nuget package has been released from the `4.0.0-beta1` tag, based from `master`

**Comment by bugnuker** [comment]
Great, Thank you!

I am working on testing it. So far, only breaking change I've seen is the property "Aaguid" changed to "AaGuid". Will post back here if I find other items. Thanks!

**Comment by bugnuker** [comment]
beta2 fails to compile with existing code - something change with the callback?

There is no argument given that corresponds to the required parameter 'isUserHandleOwnerOfCredentialIdCallback' of 'Fido2.MakeAssertionAsync(AuthenticatorAssertionRawResponse, AssertionOptions, byte[], List<byte[]>, uint, IsUserHandleOwnerOfCredentialIdAsync, CancellationToken)
