### ISSUE TITLE
Passwordless Demo failing in 4.0.0-beta2 (master)

### ISSUE THREAD

**Issue by trankin** [passwordless-lib/fido2-net-lib#402]
I found a couple of issues causing this to fail when testing the passwordless feature of the demo.

Registration is failing out of the box because when posting to /makeCredential extensions.credOpts used to be true and is now {rk: true},   This is causing a binding error on the AuthenticatorAttestationRawResponse object.

/makeCredential was further failing because when storing the credential to DemoStorage Descriptor is null because success.Result.CredentialId is no longer being populated in AuthenticatorAttestationResponse.cs.  This fails silently on registration and appears to be successful, but Sign In will fail because the credential can't be found when doing /assertionOptions.

**Comment by abergs** [comment]
Thanks for testing these issues. We have a very long running branch #277  that we need to merge. @aseigler Do you even think it's possible to merge that branch or should we just create new smaller PR's that add some of the changes you did?

**Comment by abergs** [comment]
Fixed in #411
