### ISSUE TITLE
RFC: Merge Fido2 & Fido2.Models

### ISSUE THREAD

**Issue by iamcarbon** [passwordless-lib/fido2-net-lib#420]
Is there any case where Fido2.Models would be used without the main Fido2 library -- or should we consider merging these together for the 4.0 release? 

Ping @abergs

**Comment by abergs** [comment]
Pretty sure it was to allow intermediate services to pull in types without pulling in the rest of Fido2. So long time ago I can't clearly remember the issue... Put pretty sure someone asked for it.

**Comment by dbeinder** [comment]
I'm using the Models package to implement a browserless client using the native Windows WebAuthn API: https://github.com/dbeinder/Yoq.WindowsWebAuthn
Another use case would be when you put all (de)serialization/persistence logic into a separate project.
I prefer the current split, and having a package for the transport data types that can be added without pulling in additional dependencies.

**Comment by iamcarbon** [comment]
@dbeinder @abergs Thanks for the feedback. Agree, it's nice not having to bring in the external dependencies in this case!
