### ISSUE TITLE
Migration to Microsoft.IdentityModel.JsonWebTokens

### ISSUE THREAD

**Issue by joegoldman2** [passwordless-lib/fido2-net-lib#436]
This library should migrate to `Microsoft.IdentityModel.JsonWebTokens`? As indicated [here](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki), `Microsoft.IdentityModel.JsonWebTokens` is a newer, faster version of `System.IdentityModel.Tokens.Jwt` that has additional functionality.

**Comment by iamcarbon** [comment]
Thanks for bringing this to my attention. I'll take a look at this.

**Comment by iamcarbon** [comment]
@joegoldman2 I'll take this on once the pull request backlog gets worked through to make sure we don't have any conflicts. This will require a bunch of methods be updated to async.

**Comment by iamcarbon** [comment]
Implemented in #476
