### ISSUE TITLE
Review lifecycle of services registered in the DI container

### ISSUE THREAD

**Issue by joegoldman2** [passwordless-lib/fido2-net-lib#439]
Currently `IMetadataService` is registered as a scoped service:

https://github.com/passwordless-lib/fido2-net-lib/blob/15263ca8bc4ceea84c3ef287300ac2962d9afe10/Src/Fido2.AspNet/Fido2NetLibBuilderExtensions.cs#L90

But `IFido2` and `IMetadataRepository` are registered as transient:

https://github.com/passwordless-lib/fido2-net-lib/blob/15263ca8bc4ceea84c3ef287300ac2962d9afe10/Src/Fido2.AspNet/Fido2NetLibBuilderExtensions.cs#L29

https://github.com/passwordless-lib/fido2-net-lib/blob/15263ca8bc4ceea84c3ef287300ac2962d9afe10/Src/Fido2.AspNet/Fido2NetLibBuilderExtensions.cs#L83

I think it makes sense to register `IFido2` and `IMetadataRepository` as scoped as well here.

What do you think @abergs and @iamcarbon?

**Comment by iamcarbon** [comment]
@joegoldman2  I don't see any transient dependencies on these services, and agree that they can both be scoped. Let's update.
