### ISSUE TITLE
Remove hardcoded BLOB url from `Fido2MetadataServiceRepository.cs` 

### ISSUE THREAD

**Issue by joegoldman2** [passwordless-lib/fido2-net-lib#443]
We should probably remove the hardcoded BLOB url from `Fido2MetadataServiceRepository.cs` and change this line:

https://github.com/passwordless-lib/fido2-net-lib/blob/15263ca8bc4ceea84c3ef287300ac2962d9afe10/Src/Fido2.AspNet/Fido2NetLibBuilderExtensions.cs#L78

to something like:

```cs
var httpClientBuilder = builder.Services.AddHttpClient(nameof(Fido2MetadataServiceRepository), client =>
{
    client.BaseAddress = new Uri("https://mds3.fidoalliance.org/");
});
```

This will allow users to configure the url they want (especially when a new version is available) using the `clientBuilder` delegate from `AddFidoMetadataRepository` .

What do you think @abergs  and @iamcarbon?

**Comment by aseigler** [comment]
Makes sense to me, as long as there is a default.
