### ISSUE TITLE
Where is the package `Fido2.Development`?

### ISSUE THREAD

**Issue by joegoldman2** [passwordless-lib/fido2-net-lib#452]
Since the PR #427, a new assembly `Fido2.Development` has been introduced. Then, a new version (`4.0.0-beta4`) has been released but not the package `Fido2.Development`. Is this an oversight or you don't plan to publish this package?

**Comment by abergs** [comment]
Might be an oversight, but the contents of the Development assembly is primarily used for Demo'es etc. Is there a need for a nuget package to be published?

**Comment by joegoldman2** [comment]
Obviously, this assembly is useful for demonstration purposes. I am currently using these classes for a demo project and after the migration to the version `4.0.0-beta4`, I had to copy/past them inside my project (there are just few classes so it's not a big deal). I would say, it's good to publish this assembly.

**Comment by joegoldman2** [comment]
@iamcarbon, @aseigler any opinions?

**Comment by aseigler** [comment]
I am trying to come up with an opinion on this one way or the other but I am coming up empty.  The demo stuff was never really supposed to be used for real, it was just to show that it works and how it works.  By putting it in a package, that kind of encourages people to use it as is, and that was not the initial intent.

**Comment by iamcarbon** [comment]
I don't think it makes sense to ship (and commit to maintaining) any developer, demo, or testing classes. They shouldn't be used in production.

For anyone building their own fido2 demos or prototypes, the sources can be easily cloned and modified, as needed.
