### ISSUE TITLE
Question: Webauthn PRF Extension browser support?

### ISSUE THREAD

**Issue by mangoplane** [passwordless-lib/fido2-net-lib#457]
Hi,

Has anyone been able to successfully get the Webauthn PRF Extension working? Anyone know the support status across mobile devices and browsers?
This single extension will unlock so many possibilities, and I'm looking forward to the day it has wide support.

**Comment by aseigler** [comment]
I know a guy https://blog.millerti.me/2023/01/22/encrypting-data-in-the-browser-using-webauthn/
