### ISSUE TITLE
Enable nullable for Fido2.Models

### ISSUE THREAD

**Issue by dradovic** [passwordless-lib/fido2-net-lib#466]
I would be really helpful to annotate the nullability of the `Fido2.Models` types. In other words, to set `<Nullable>enable</Nullable>` in the `Fido2.Models` project.

This way, it would become clear for FIDO2 newbies to understand which information is optional and which one is required.

For example, in the demo, you have a line of code that stores a credential coming from `MakeNewCredentialAsync`:

    DevicePublicKeys = new List<byte[]>() { success.Result.DevicePublicKey }

If both `Fido2.Models` and `Demo` were NRT enabled, this would pop up as a compilation error. Righteously so, because I don't think it make sense to store a list containing a `null` along the credential. So in this example, it would really help if `RegisteredPublicKeyCredential.DevicePubliKey` was declared as `byte[]?`. And I assume there's plenty more.

**Comment by iamcarbon** [comment]
We can't use required members yet (the net6.0 system.text.json source generator doesn't support them) -- so there's no clean way to annotate non-null members in the models library right now.

We should, however, continue to annotate nullable members inside of #nullable enable blocks. If we drop net6.0 when it goes out of support, it should be trivial to annotate the remaining members.

**Comment by dradovic** [comment]
Yes. I guess the first step should be to have `<Nullable>enable</Nullable>` in the `Fido2.Models` project (just as you already have it in the `Fido2` project). This issue is about that.

And then in a later step, the `require` keyword can be used to make sure that props are correctly initialized.
`

**Comment by iamcarbon** [comment]
Hi @dradovic!

Until we can use required properties, I would suggest that we limit the annotations to properties we know can be null inside of a nullable enable pragma.  There are ~114 properties that we are unable to annotate on this project due to the json serializer limitations, and opting the project into <nullable> will require a lot of suppressions that we are unable to resolve.

For example:

```
// we cannot mark this as required, so if we enable nullable at the project level, we'd have to disable nullable here.
[JsonPropertyName("nextUpdate"), Required]
public string NextUpdate { get; set; }
  
// and then reenable again.
#nullable enable
public string? SomethingWeKnowIsNullable { get; set; } 
#nullable disable

// Not enabling it at the project level allows us to skip the additional suppressions until we're able to mark the members as required
```

**Comment by abergs** [comment]
@iamcarbon As November 12th is coming up, marking the end of LTS .net6 - is there anything we should do here?
