### ISSUE TITLE
signing entries in a ledger or dag

### ISSUE THREAD

**Issue by unicomp21** [passwordless-lib/fido2-net-lib#469]
Is it possible to use the auth mechanism for signing ledger/dag entries? ie replace the seqno/counter w/ a sha-3-512 ?

**Comment by iamcarbon** [comment]
@abergs Any chance we can enable discussions on the project (https://docs.github.com/en/discussions/quickstart) and move this topic here?

**Comment by abergs** [comment]
Enabled - please post your general questions there: https://github.com/passwordless-lib/fido2-net-lib/discussions
