### ISSUE TITLE
Android support for DevicePubKey extension

### ISSUE THREAD

**Issue by thomasnymand** [passwordless-lib/fido2-net-lib#470]
I am having issues testing the use of the DevicePubKey proposed extension ([DevicePubKey](https://pr-preview.s3.amazonaws.com/w3c/webauthn/pull/1663.html#sctn-device-publickey-extension)) that seems to be supported (although the documentation for AuthenticationsExtensionsClientInputs.DevicePubKey is misleading). UserController enables this extension.

I am not able to retrieve any extension responses from neither create() nor get() methods when passing this extension to client where support should be enabled (Chrome on recent Android, cf. [Security of Passkey in Google Password Manager](https://security.googleblog.com/2022/10/SecurityofPasskeysintheGooglePasswordManager.html) ).

Does anybody have experience in using this extension successfully?

**Comment by abergs** [comment]
Device Pubkey has been dropped from the L3 WebAuthn spec.
