### ISSUE TITLE
Newtonsoft Package for Fido2.Model

### ISSUE THREAD

**Issue by mahdiit** [passwordless-lib/fido2-net-lib#473]
I found that all fido2.model is based on system.text.json but in some project we need same but with Newtonsoft JSON
and all desterilize  dot not work because of JSON attribute

**Comment by iamcarbon** [comment]
This library has a strong dependency on System.Text.Json for its serialization features, including its source generator to enable AOT support. Newtonsoft is not supported.

What prevents you from using System.Text.Json to deserialize the Fido models?

**Comment by mahdiit** [comment]
I have a project that already config controllers, serializer and other models with Newtonsoft,
 it is a suggestion if possible and not a request

I changed some section and start to create another project for better compatibility with system.text.json
