### ISSUE TITLE
Rename some types to match the specification

### ISSUE THREAD

**Issue by joegoldman2** [passwordless-lib/fido2-net-lib#482]
Currently, some type names don't fully match the specification. That's not a problem, but I think it would be a good idea to rename them to make them easier to understand:
- `CredentialCreateOptions` => `PublicKeyCredentialCreationOptions`
- `AssertionOptions` => `PublicKeyCredentialRequestOptions`

What do you think?

**Comment by abergs** [comment]
I'm not convinced of this change. To me those names are less readable although I often think we should keep close to spec.

**Comment by jonashendrickx** [comment]
I found the names in the official specification to be quite confusing. I kept misreading PublicKeyCredentialCreationOptions and PublicKeyCredentialRequestOptions, wrongly interchanging them.
