### ISSUE TITLE
.NET 8 Support

### ISSUE THREAD

**Issue by No1e** [passwordless-lib/fido2-net-lib#486]
Hello,

do you plan supporting .NET 8? Is there roadmap for that?

Best regards,
Novak

**Comment by jonashendrickx** [comment]
Hi @No1e, it was merged in with #468

**Comment by No1e** [comment]
@jonashendrickx Thank you very much. Can you tell me when to you plan new version of NuGet package?

**Comment by abergs** [comment]
@No1e There's a preview package available on nuget. There is no deadline for v4 stable, but we're still waiting for some packages to drop.
