### ISSUE TITLE
Semantic Versioning is not properly followed

### ISSUE THREAD

**Issue by joegoldman2** [passwordless-lib/fido2-net-lib#487]
The recent beta releases do not follow semantic versioning properly. The absence of a dot before the numerical identifier in `beta10` causes it not to be recognized as the next version after `beta9`. To adhere to semantic versioning conventions, a dot should be introduced before the numerical identifier for beta versions, like `4.0.0-beta.10`, so NuGet can detect the update.

![image](https://github.com/passwordless-lib/fido2-net-lib/assets/147369450/3d7139ec-aed0-47c2-842a-0b1a1ade0c14)

**Comment by abergs** [comment]
Oh, I didn't know. Thanks for the tip. Will do so in future relelases.

**Comment by Tyrrrz** [comment]
Appears that the dot didn't help:

![image](https://github.com/passwordless-lib/fido2-net-lib/assets/1935960/2c862d06-ec8d-46da-9664-371db74824a4)

**Comment by joegoldman2** [comment]
The correct syntax is with a dot like:

![image](https://github.com/passwordless-lib/fido2-net-lib/assets/147369450/0a0949c7-1305-4814-9156-927525632b0e)

Versions without will always be considered as the next ones and must surely be unlisted.
