### ISSUE TITLE
Community Feedback on requiring .NET8.0 for v4 release

### ISSUE THREAD

**Issue by iamcarbon** [passwordless-lib/fido2-net-lib#497]
Considering that .NET 6.0 is going out of support on November 12, 2024, what does everyone think of dropping .NET6.0 support for the 4.0 release -- and bringing the minimum target to .NET 8.0.

.NET 8.0 is the current LTM release, and will be supported until November 10, 2026.

**Comment by nico81cn** [comment]
I agree

**Comment by nico81cn** [comment]
(Some news on final 4.0 release date?)

**Comment by abergs** [comment]
@nico81cn No but you're welcome to use the beta's.

**Comment by alexeygritsenko** [comment]
I like. Are there plans to support Windows Hello for Business?

**Comment by aseigler** [comment]
> I like. Are there plans to support Windows Hello for Business?

That's been supported for years, both RSA and ECC keys, in all the various attestation formats it produces.

**Comment by abergs** [comment]
@aseigler Any veto or are you OK moving to .net 8?

**Comment by aseigler** [comment]
I have no issue with this.
