### ISSUE TITLE
StoredCredential no longer contains the CredType property - migrating stored credentials from 3.0.1 to 4.0.0

### ISSUE THREAD

**Issue by g7ed6e** [passwordless-lib/fido2-net-lib#515]
Hello, I'm upgrading an application from 3.0.1 to 4.0.0-beta.12 and noticed the CredType property is no longer present in the StoredCredential type (which i mapped to a database table).
Also i noticed that some new properties are now present in StoredCredential. 
I'm wondering what the migration path would be from 3.0.1 to 4.0.0.

**Comment by abergs** [comment]
@g7ed6e StoredCredential is intended to be used in our demo's and not in production databases. We do don't advertise or "support" breaking changes in the StoredCredential class.

Please have a look at the "RegisteredPublicKeyCredential" class that we output from the library and use that to map to your database or your own version of "StoredCredential".
