### ISSUE TITLE
Support for authenticatorDisplayName (Client extension output)

### ISSUE THREAD

**Issue by maui1911** [passwordless-lib/fido2-net-lib#523]
`authenticatorDisplayName, of type [USVString](https://webidl.spec.whatwg.org/#idl-USVString)`

This OPTIONAL property is a [human-palatable](https://w3c.github.io/webauthn/#human-palatability) description of the credential’s [managing authenticator](https://w3c.github.io/webauthn/#public-key-credential-source-managing-authenticator), chosen by the user.

The [client](https://w3c.github.io/webauthn/#client) MUST allow the user to choose this value. That choice MAY be presented during the [registration](https://w3c.github.io/webauthn/#registration-ceremony) or [authentication](https://w3c.github.io/webauthn/#authentication-ceremony) ceremony or MAY be made available outside the ceremony, for example in client settings. The [client](https://w3c.github.io/webauthn/#client) MAY reuse the same value for multiple credentials with the same [managing authenticator](https://w3c.github.io/webauthn/#public-key-credential-source-managing-authenticator) across multiple [Relying Parties](https://w3c.github.io/webauthn/#relying-party).

The [client](https://w3c.github.io/webauthn/#client) MAY query the [authenticator](https://w3c.github.io/webauthn/#authenticator), by some unspecified mechanism, for this value. The [authenticator](https://w3c.github.io/webauthn/#authenticator) MAY allow the user to configure the response to such a query. The [authenticator](https://w3c.github.io/webauthn/#authenticator) vendor MAY provide a default response to such a query. The [client](https://w3c.github.io/webauthn/#client) MAY consider a user-configured response chosen by the user, and SHOULD allow the user to modify a vendor-provided default response.

If the [Relying Party](https://w3c.github.io/webauthn/#relying-party) includes an [authenticatorDisplayName](https://w3c.github.io/webauthn/#abstract-opdef-credential-record-authenticatordisplayname) [item](https://infra.spec.whatwg.org/#struct-item) in its [credential records](https://w3c.github.io/webauthn/#credential-record), the [Relying Party](https://w3c.github.io/webauthn/#relying-party) MAY offer this [authenticatorDisplayName](https://w3c.github.io/webauthn/#dom-credentialpropertiesoutput-authenticatordisplayname) extension output, if present, as a default value for the [authenticatorDisplayName](https://w3c.github.io/webauthn/#abstract-opdef-credential-record-authenticatordisplayname) of the new [credential record](https://w3c.github.io/webauthn/#credential-record) it stores after a [registration ceremony](https://w3c.github.io/webauthn/#registration-ceremony).

If the [authenticatorDisplayName](https://w3c.github.io/webauthn/#dom-credentialpropertiesoutput-authenticatordisplayname) extension output from an [authentication ceremony](https://w3c.github.io/webauthn/#authentication-ceremony) is different from the [authenticatorDisplayName](https://w3c.github.io/webauthn/#abstract-opdef-credential-record-authenticatordisplayname) of the [credential record](https://w3c.github.io/webauthn/#credential-record), the [Relying Party](https://w3c.github.io/webauthn/#relying-party) MAY offer the user to update the [authenticatorDisplayName](https://w3c.github.io/webauthn/#abstract-opdef-credential-record-authenticatordisplayname) of the [credential record](https://w3c.github.io/webauthn/#credential-record).

https://w3c.github.io/webauthn/#dom-credentialpropertiesoutput-authenticatordisplayname

**Comment by jonashendrickx** [comment]
https://github.com/passwordless-lib/fido2-net-lib/pull/526

**Comment by maui1911** [comment]
Nice
