### ISSUE TITLE
Allow dev to customize what algo's they support instead of hard coding in CredentialCreateOptions

### ISSUE THREAD

**Issue by abergs** [passwordless-lib/fido2-net-lib#533]
For conformance we must support RS1, but it should be left out from being enabled by default (suggested by @aseigler, could you expand the reasoning for disabling RS1?)

**Comment by aseigler** [comment]
It's deprecated https://www.iana.org/assignments/cose/cose.xhtml#algorithms, it uses SHA1, so it's not recommended for use, but the conformance testing requires it be supported for...reasons.
