### ISSUE TITLE
Seems like the latest change has broken the demo project.

### ISSUE THREAD

**Issue by bgirts** [passwordless-lib/fido2-net-lib#534]
Hi! 

![image](https://github.com/user-attachments/assets/22aa7f8a-b50d-48a2-af88-90abb533cf78)

The registration js file still relies on "ok" status, thus demo project is broken. 

![image](https://github.com/user-attachments/assets/2746c3a4-f612-4fe8-ab36-3f153273e0d4)

Probably changing to this should fix the issue, at least quick local change seems to work for me. 

![image](https://github.com/user-attachments/assets/a27989de-2690-4242-9e37-20deb84156a6)

# Error details #

![image](https://github.com/user-attachments/assets/711f0567-bce2-4d58-8563-51bb6bf03e42)
![image](https://github.com/user-attachments/assets/8d5db288-94dc-4058-8fbc-ed8af8c7b815)
![image](https://github.com/user-attachments/assets/b2b51e4c-e431-4791-8de8-45a6f0f29025)

**Comment by abergs** [comment]
Agreed, demo is currently a bit out of sync with the API.

**Comment by andrew-armitage** [comment]
I just tried to run this and found that there is no 'Status' field in the data. Looking at the js, status refers to the status code from the API and only the data is taken from the response.

**Comment by abergs** [comment]
@andrew-armitage Yes, a fix is incoming.
