### ISSUE TITLE
Is there a release timeline for v4?

### ISSUE THREAD

**Issue by markphillips100** [passwordless-lib/fido2-net-lib#559]
I don't mean to apply pressure at all by my title question.  I totally understand this is OSS and people have other lives, both inside and out of work.  All I'm asking is if there is a plan to release soon, or if not is there a specific breaking feature missing that would preclude it?

I have a working use case using 4.0.0-beta.13 but I'm obviously reluctant to commit my use of a beta package without some guarantees on changes.

**Comment by abergs** [comment]
There is no time commitment. But w heave landed the lost significant changes for V4. Beta 13 already contains many of them, 14 will contain some API signature changes.

Might be the last beta, but no promises. 

In an ideal world we ship 4.0 this year.
