### ISSUE TITLE
Zip Download doesn't contain .git directory, causing sourcelink build failure.

### ISSUE THREAD

**Issue by briansboyd** [passwordless-lib/fido2-net-lib#72]
Since this project uses sourcelink, the .git directory must be present.
That is, since this directory isn't in the zip file, the build fails with the below errors:
![image](https://user-images.githubusercontent.com/576897/50883449-71636780-142b-11e9-9bd4-f7a01b588cbe.png)

**Comment by abergs** [comment]
For clarification: This problem arises when downloading the repo from github using the zip alternative rather than a clone. @MeikTranel Have you seen this before? Know a workaround?

**Comment by MeikTranel** [comment]
Haven't seen this with sourcelink but other software though. Some times even CICD service providers act like this. The error message makes sense though I didn't know that it would fail the build that way.
I'll check this tomorrow, if this a known issue with sourcelink or if there's a workaround.

**Comment by MeikTranel** [comment]
So the use-case is you want your build to not fail when downloading the zip from which is understandable.

I'd just say we put a condition on it, checking if the .git directory or .gitconfig file for worktrees is present and if not just disable sourcelink with a warning?

**Comment by abergs** [comment]
I think that sounds like a good plan. The warning is a nice touch 👍

**Comment by abergs** [comment]
@MeikTranel is this possible to do? I have no idea how to do it myself so i'm just leaving this open

**Comment by CodeTherapist** [comment]
@briansboyd To mitigate the situation for you, you could disable source link by adding a property in the [Fido2NetLib.csproj](https://github.com/abergs/fido2-net-lib/blob/cb50a857af6a1f690a1b41df7f0e4d589922a727/fido2-net-lib/Fido2NetLib.csproj#L1):

`<EnableSourceLink>false</EnableSourceLink>`

**Comment by briansboyd** [comment]
Thanks @CodeTherapist, we've since just cloned the repo.

**Comment by aseigler** [comment]
Should be resolved.
