### ISSUE TITLE
Extract interface from Fido2 class to allow creating Mock<IFido2>

### ISSUE THREAD

**Issue by briansboyd** [passwordless-lib/fido2-net-lib#91]
Many people use Moq when writing Unit Tests.  Extracting an interface from the Fido2 class will allow the Fido2 class to be mocked, making it easier for many users to write unit tests for their components that use the Fido2 library.

**Comment by briansboyd** [comment]
I'm happy to contribute the pull request, just tell me which branch to make the change in.  Cheers.

**Comment by abergs** [comment]
@briansboyd master

**Comment by briansboyd** [comment]
Moved to another company, no longer working with Fido2.  Good luck with this project!

**Comment by Regenhardt** [comment]
`IFido2` interface exists, I guess this happened some time after this issue was created, can this be closed then?
